/******************************************************************************
 *
 *                          Copyright 2021 Siemens
 *                           All Rights Reserved
 *
 * THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY INFORMATION WHICH IS
 * THE PROPERTY OF SIEMENS OR ITS LICENSORS AND IS SUBJECT TO LICENSE TERMS.
 *
 ******************************************************************************
 *
 * This file is automatically generated by VSC.
 * Do not edit manually!
 * VSC Version:  2.6.8
 * BswMPlugin:   com.mentor.bsw.bswm.generator 5.18.0
 *
 ******************************************************************************
 *
 * Module:       BswM
 *
 * File Name:    BswM_Types.h
 *
 * Description:  Type definitions of the BswM module.
 *
 ******************************************************************************/

#ifndef BSWM_TYPES_H
#define BSWM_TYPES_H

/*=============================== INCLUSIONS =================================*/

#include "BswM_Version.h"

#include "BswM_Cfg.h"

#include "Std_Types.h"
#include "ComStack_Types.h"

/*============================ TYPE DEFINITIONS ==============================*/

/**
 * Forward declaration for internal types referred
 * by the public 'BswM_ConfigType' structure.
 */
typedef struct BswM_RulePBPropertiesType_TAG        BswM_RulePBPropertiesType;
typedef struct BswM_ActionListType_TAG              BswM_ActionListType;

/**
 * This structure contains all post-build configurable parameters of the
 * BSW Mode Manager. A pointer to this structure is passed to the BSW Mode
 * Manager initialization function for configuration.
 * [SWS_BSWM-00042] [SWS_BSWM-00213]
 */
typedef struct BswM_ConfigType_TAG
{


    /* Pointer to the structure array holding constant Post-Build properties of each Rule */
    CONSTP2CONST(BswM_RulePBPropertiesType, TYPEDEF, BSWM_CONST) ptrRulePBProperties;

    /* Pointer to BswM Action list structure used in the BswM_action.c file */
    CONSTP2CONST(BswM_ActionListType, TYPEDEF, BSWM_CONST) ptrAllActionLists;

    /* Pointer to the Pre-Compile Hash Value */
    CONSTP2CONST(uint32, TYPEDEF, BSWM_CONST) ptrPBtoPCHashValue;

    /* Pointer to the Link-Time Hash Value */
    CONSTP2CONST(uint32, TYPEDEF, BSWM_CONST) ptrPBtoLTHashValue;

} BswM_ConfigType;

/*============================ MACRO DEFINITIONS =============================*/

/*===================== EXTERNAL VARIABLE DECLARATIONS =======================*/

/*===================== EXTERNAL FUNCTION DECLARATIONS =======================*/

#endif /* BSWM_TYPES_H */
/*========================= END OF FILE BswM_Types.h =========================*/
