/******************************************************************************
 *
 *                          Copyright 2021 Siemens
 *                           All Rights Reserved
 *
 * THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY INFORMATION WHICH IS
 * THE PROPERTY OF SIEMENS OR ITS LICENSORS AND IS SUBJECT TO LICENSE TERMS.
 *
 ******************************************************************************
 *
 * This file is automatically generated by VSC.
 * Do not edit manually!
 * VSC Version:  2.6.8
 * BswMPlugin:   com.mentor.bsw.bswm.generator 5.18.0
 *
 ******************************************************************************
 *
 * Module:       BswM
 *
 * File Name:    BswM_PBcfg.h
 *
 * Description:  Contains declaration of public Post-Build symbols.
 *
 ******************************************************************************/

#ifndef BSWM_PBCFG_H
#define BSWM_PBCFG_H

/*=============================== INCLUSIONS =================================*/

#include "BswM_GeneratedTypes.h"

/*============================== VERSION INFO ================================*/

#define BSWM_PBCFG_SW_MAJOR_VERSION            (5U)
#define BSWM_PBCFG_SW_MINOR_VERSION            (18U)
#define BSWM_PBCFG_SW_PATCH_VERSION            (0U)

/*============================ TYPE DEFINITIONS ==============================*/

/*============================ MACRO DEFINITIONS =============================*/

/*===================== EXTERNAL VARIABLE DECLARATIONS =======================*/

#define BSWM_START_SEC_POSTBUILD_CONST_UNSPECIFIED
#include "BswM_MemMap.h"

/**
 * Extern declaration for the main Post-Build configuration structure.
 */
extern CONST(BswM_ConfigType, BSWM_CONFIG_DATA) BswMConfig;

#define BSWM_STOP_SEC_POSTBUILD_CONST_UNSPECIFIED
#include "BswM_MemMap.h"


/*===================== EXTERNAL FUNCTION DECLARATIONS =======================*/

#endif /* BSWM_PBCFG_H */
/*========================= END OF FILE BswM_PBcfg.h =========================*/
