/******************************************************************************
 *
 *                          Copyright 2021 Siemens
 *                           All Rights Reserved
 *
 * THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY INFORMATION WHICH IS
 * THE PROPERTY OF SIEMENS OR ITS LICENSORS AND IS SUBJECT TO LICENSE TERMS.
 *
 ******************************************************************************
 *
 * This file is automatically generated by VSC.
 * Do not edit manually!
 * VSC Version:  2.6.8
 * BswMPlugin:   com.mentor.bsw.bswm.generator 5.18.0
 *
 ******************************************************************************
 *
 * Module:       BswM
 *
 * File Name:    BswM.h
 *
 * Description:  Contains declaration of public API functions.
 *
 * Requirements: [SWS_BSWM-00026.v4]
 *
 ******************************************************************************/

#ifndef BSWM_H
#define BSWM_H

/*=============================== INCLUSIONS =================================*/

#include "BswM_Types.h"

#ifndef VSTAR_BSW_STATIC_SOURCE
  #include "BswM_Lcfg.h"
#endif
#if !defined(VSTAR_BSW_STATIC_SOURCE) && !defined(VSTAR_BSW_LCFG_SOURCE) && !defined(BSWM_BSW_LCFG_SOURCE)
  #include "BswM_PBcfg.h"
#endif

/*============================ TYPE DEFINITIONS ==============================*/

/*============================== VERSION INFO ================================*/

/*============================ MACRO DEFINITIONS =============================*/

/** Development error codes - [SWS_BSWM-00230.v2] ******************************/

/* A service was called prior to initialization */
#define BSWM_E_NO_INIT                              ((uint8) 0x01U)

/* A null pointer was passed as an argument */
#define BSWM_E_NULL_POINTER                         ((uint8) 0x02U)

/* A requesting user was out of range */
#define BSWM_E_REQ_USER_OUT_OF_RANGE                ((uint8) 0x04U)

/* A requested mode was out of range */
#define BSWM_E_REQ_MODE_OUT_OF_RANGE                ((uint8) 0x05U)

/* The provided configuration is inconsistent */
#define BSWM_E_PARAM_CONFIG                         ((uint8) 0x06U)

/** Custom Development Error Codes used by BswM */

/* API called on an unexpected OsApplication */
#define BSWM_E_INVALID_APPLICATION                  ((uint8) 0x20U)

/** API Service IDs ***********************************************************/

#define BSWM_INIT_API_ID                            ((uint8) 0x00U)
#define BSWM_GETVERSIONINFO_API_ID                  ((uint8) 0x01U)
#define BSWM_MAINFUNCTION_API_ID                    ((uint8) 0x03U)
#define BSWM_DEINIT_API_ID                          ((uint8) 0x04U)

#define BSWM_CANSM_API_ID                           ((uint8) 0x05U)
#define BSWM_COMM_API_ID                            ((uint8) 0x0eU)
#define BSWM_COMMPNC_API_ID                         ((uint8) 0x15U)
#define BSWM_DCMCOM_API_ID                          ((uint8) 0x06U)
#define BSWM_ECUM_API_ID                            ((uint8) 0x0fU)
#define BSWM_ECUMWAKEUP_API_ID                      ((uint8) 0x10U)
#define BSWM_ETHIF_API_ID                           ((uint8) 0x26U)
#define BSWM_ETHSM_API_ID                           ((uint8) 0x0dU)
#define BSWM_FRSM_API_ID                            ((uint8) 0x0cU)
#define BSWM_GENERICREQUEST_API_ID                  ((uint8) 0x02U)
#define BSWM_LINSM_API_ID                           ((uint8) 0x09U)
#define BSWM_LINSCHEDULE_API_ID                     ((uint8) 0x0aU)
#define BSWM_LINTP_API_ID                           ((uint8) 0x0bU)
#define BSWM_NVMJOB_API_ID                          ((uint8) 0x17U)
#define BSWM_NVMBLOCK_API_ID                        ((uint8) 0x16U)
#define BSWM_PARTITIONRESTARTED_API_ID              ((uint8) 0x1eU)
#define BSWM_SDCLIENTSERVICE_API_ID                 ((uint8) 0x1fU)
#define BSWM_SDEVENTGROUP_API_ID                    ((uint8) 0x21U)
#define BSWM_SDEVENTHANDLER_API_ID                  ((uint8) 0x20U)
#define BSWM_WDGM_API_ID                            ((uint8) 0x11U)

/*===================== EXTERNAL VARIABLE DECLARATIONS =======================*/

/*===================== EXTERNAL FUNCTION DECLARATIONS =======================*/

#define BSWM_START_SEC_CODE
#include "BswM_MemMap.h"

FUNC(Std_ReturnType, BSWM_CODE) BswM_ConsistencyCheck
(
    P2CONST(BswM_ConfigType, AUTOMATIC, BSWM_CONST) ConfigPtr
);

FUNC(void, BSWM_CODE) BswM_Init
(
    P2CONST(BswM_ConfigType, AUTOMATIC, BSWM_CONST) ConfigPtr
);

FUNC(void, BSWM_CODE) BswM_Deinit( void );

FUNC(void, BSWM_CODE) BswM_GetVersionInfo
(
    P2VAR(Std_VersionInfoType, AUTOMATIC, BSWM_APPL_DATA) VersionInfo
);

#define BSWM_STOP_SEC_CODE
#include "BswM_MemMap.h"

#endif /* BSWM_H */
/*========================== END OF FILE BswM.h ==============================*/
