/******************************************************************************
 *
 *                          Copyright 2020 Siemens
 *                           All Rights Reserved
 *
 * THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY INFORMATION WHICH IS
 * THE PROPERTY OF SIEMENS OR ITS LICENSORS AND IS SUBJECT TO LICENSE TERMS.
 *
 ******************************************************************************
 *
 * Module:      MemMap
 *
 * File Name:   BswM_MemMap.h
 *
 * Description: Memory mapping header file.
 *
 *              NOTE! This file is automatically generated!
 *              Do NOT edit manually!
 *
 ******************************************************************************/


/*=============================== INCLUSIONS =================================*/

/*============================ TYPE DEFINITIONS ==============================*/

/*============================== VERSION INFO ================================*/

/** General Information *******************************************************/

#ifdef MEMMAP_VENDOR_ID
  #if (MEMMAP_VENDOR_ID != 31U)
    #error "Redefinition of MEMMAP_VENDOR_ID macro with different value!"
  #endif
#else
  #define MEMMAP_VENDOR_ID                     (31U)
#endif

#ifdef MEMMAP_MODULE_ID
  #if (MEMMAP_MODULE_ID != 195U)
    #error "Redefinition of MEMMAP_MODULE_ID macro with different value!"
  #endif
#else
  #define MEMMAP_MODULE_ID                     (195U)
#endif


/** AUTOSAR Version Information ***********************************************/

#ifdef MEMMAP_AR_RELEASE_MAJOR_VERSION
  #if (MEMMAP_AR_RELEASE_MAJOR_VERSION != 4U)
    #error "Redefinition of MEMMAP_AR_RELEASE_MAJOR_VERSION macro with different value!"
  #endif
#else
  #define MEMMAP_AR_RELEASE_MAJOR_VERSION      (4U)
#endif

#ifdef MEMMAP_AR_RELEASE_MINOR_VERSION
  #if (MEMMAP_AR_RELEASE_MINOR_VERSION != 2U)
    #error "Redefinition of MEMMAP_AR_RELEASE_MINOR_VERSION macro with different value!"
  #endif
#else
  #define MEMMAP_AR_RELEASE_MINOR_VERSION      (2U)
#endif

#ifdef MEMMAP_AR_RELEASE_REVISION_VERSION
  #if (MEMMAP_AR_RELEASE_REVISION_VERSION != 2U)
    #error "Redefinition of MEMMAP_AR_RELEASE_REVISION_VERSION macro with different value!"
  #endif
#else
  #define MEMMAP_AR_RELEASE_REVISION_VERSION   (2U)
#endif


/** Software Version Information **********************************************/

#ifdef MEMMAP_SW_MAJOR_VERSION
  #if (MEMMAP_SW_MAJOR_VERSION != 3U)
    #error "Redefinition of MEMMAP_SW_MAJOR_VERSION macro with different value!"
  #endif
#else
  #define MEMMAP_SW_MAJOR_VERSION              (3U)
#endif

#ifdef MEMMAP_SW_MINOR_VERSION
  #if (MEMMAP_SW_MINOR_VERSION != 10U)
    #error "Redefinition of MEMMAP_SW_MINOR_VERSION macro with different value!"
  #endif
#else
  #define MEMMAP_SW_MINOR_VERSION              (10U)
#endif

#ifdef MEMMAP_SW_PATCH_VERSION
  #if (MEMMAP_SW_PATCH_VERSION != 2U)
    #error "Redefinition of MEMMAP_SW_PATCH_VERSION macro with different value!"
  #endif
#else
  #define MEMMAP_SW_PATCH_VERSION              (2U)
#endif


/*============================ MACRO DEFINITIONS =============================*/

#define MEMMAP_SECTION_NOT_FOUND

#if 0

/******************************************************************************/
/** BSWM BSW                                                                 **/
/******************************************************************************/

/** BSWM - CODE ***************************************************************/
#elif defined BSWM_STOP_SEC_CODE
    #if defined BSWM_START_SEC_CODE
        #undef BSWM_START_SEC_CODE /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef BSWM_STOP_SEC_CODE /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "BSWM_STOP_SEC_CODE: This section has not been previously started!"
    #endif
#elif defined BSWM_START_SEC_CODE
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "BSWM_START_SEC_CODE: Another section which is previously started has not been stopped!"
    #endif

/** BSWM - CONFIG_DATA_UNSPECIFIED ********************************************/
#elif defined BSWM_STOP_SEC_CONFIG_DATA_UNSPECIFIED
    #if defined BSWM_START_SEC_CONFIG_DATA_UNSPECIFIED
        #undef BSWM_START_SEC_CONFIG_DATA_UNSPECIFIED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef BSWM_STOP_SEC_CONFIG_DATA_UNSPECIFIED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "BSWM_STOP_SEC_CONFIG_DATA_UNSPECIFIED: This section has not been previously started!"
    #endif
#elif defined BSWM_START_SEC_CONFIG_DATA_UNSPECIFIED
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "BSWM_START_SEC_CONFIG_DATA_UNSPECIFIED: Another section which is previously started has not been stopped!"
    #endif

/** BSWM - POSTBUILD_CONST_UNSPECIFIED ****************************************/
#elif defined BSWM_STOP_SEC_POSTBUILD_CONST_UNSPECIFIED
    #if defined BSWM_START_SEC_POSTBUILD_CONST_UNSPECIFIED
        #undef BSWM_START_SEC_POSTBUILD_CONST_UNSPECIFIED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef BSWM_STOP_SEC_POSTBUILD_CONST_UNSPECIFIED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "BSWM_STOP_SEC_POSTBUILD_CONST_UNSPECIFIED: This section has not been previously started!"
    #endif
#elif defined BSWM_START_SEC_POSTBUILD_CONST_UNSPECIFIED
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "BSWM_START_SEC_POSTBUILD_CONST_UNSPECIFIED: Another section which is previously started has not been stopped!"
    #endif

/** BSWM - VAR_NO_INIT_UNSPECIFIED ********************************************/
#elif defined BSWM_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
    #if defined BSWM_START_SEC_VAR_NO_INIT_UNSPECIFIED
        #undef BSWM_START_SEC_VAR_NO_INIT_UNSPECIFIED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef BSWM_STOP_SEC_VAR_NO_INIT_UNSPECIFIED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "BSWM_STOP_SEC_VAR_NO_INIT_UNSPECIFIED: This section has not been previously started!"
    #endif
#elif defined BSWM_START_SEC_VAR_NO_INIT_UNSPECIFIED
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "BSWM_START_SEC_VAR_NO_INIT_UNSPECIFIED: Another section which is previously started has not been stopped!"
    #endif

/** BSWM - VAR_INIT_8 *********************************************************/
#elif defined BSWM_STOP_SEC_VAR_INIT_8
    #if defined BSWM_START_SEC_VAR_INIT_8
        #undef BSWM_START_SEC_VAR_INIT_8 /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef BSWM_STOP_SEC_VAR_INIT_8 /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "BSWM_STOP_SEC_VAR_INIT_8: This section has not been previously started!"
    #endif
#elif defined BSWM_START_SEC_VAR_INIT_8
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "BSWM_START_SEC_VAR_INIT_8: Another section which is previously started has not been stopped!"
    #endif

/******************************************************************************/
/** BswM SWC                                                                 **/
/******************************************************************************/

/** BswM - CODE ***************************************************************/
#elif defined BswM_STOP_SEC_CODE
    #if defined BswM_START_SEC_CODE
        #undef BswM_START_SEC_CODE /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef BswM_STOP_SEC_CODE /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "BswM_STOP_SEC_CODE: This section has not been previously started!"
    #endif
#elif defined BswM_START_SEC_CODE
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "BswM_START_SEC_CODE: Another section which is previously started has not been stopped!"
    #endif

#endif


#if defined MEMMAP_SECTION_NOT_FOUND
    #error "Section not found in BswM_MemMap.h"
#endif

/*====================== EXTERNAL VARIABLE DECLARATIONS ======================*/

/*====================== EXTERNAL FUNCTION DECLARATIONS ======================*/

/*======================== END OF FILE BswM_MemMap.h =========================*/

/* KW MISRA.INCGUARD VIOLATION AUTOSAR requirement to be implemented this way.
   Neither executable code nor symbols are included (only pragmas), thus this violation is
   an approved exception without side effects. */

/* KW MISRA.PRAGMA VIOLATION Each #pragma usage comes from user configuration */
