/******************************************************************************
 *
 *                          Copyright 2021 Siemens
 *                           All Rights Reserved
 *
 * THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY INFORMATION WHICH IS
 * THE PROPERTY OF SIEMENS OR ITS LICENSORS AND IS SUBJECT TO LICENSE TERMS.
 *
 ******************************************************************************
 *
 * This file is automatically generated by VSC.
 * Do not edit manually!
 * VSC Version:  2.6.8
 * BswMPlugin:   com.mentor.bsw.bswm.generator 5.18.0
 *
 ******************************************************************************
 *
 * Module:       BswM
 *
 * File Name:    BswM_Swc.h
 *
 * Description:  Contains declaration of internally used, SWC related functions.
 *
 ******************************************************************************/

#ifndef BSWM_SWC_H
#define BSWM_SWC_H

/*=============================== INCLUSIONS =================================*/

#include "BswM_GeneratedTypes.h"

/*============================== VERSION INFO ================================*/

#define BSWM_SWC_SW_MAJOR_VERSION              (5U)
#define BSWM_SWC_SW_MINOR_VERSION              (18U)
#define BSWM_SWC_SW_PATCH_VERSION              (0U)

/*============================ TYPE DEFINITIONS ==============================*/

/*============================ MACRO DEFINITIONS =============================*/

/*===================== EXTERNAL VARIABLE DECLARATIONS =======================*/

#define BSWM_START_SEC_VAR_NO_INIT_UNSPECIFIED
#include "BswM_MemMap.h"




extern VAR(BswM_BswNotificationCurrentStateType0, BSWM_VAR_NO_INIT) BswM_BswNotification_MRP_EcuMode_SingleCore;


#define BSWM_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
#include "BswM_MemMap.h"


/*===================== EXTERNAL FUNCTION DECLARATIONS =======================*/

#define BSWM_START_SEC_CODE
#include "BswM_MemMap.h"

/** Initliaze all internal variables related to the 'BswMBswModeNotification' type Mode Request Ports */
FUNC(void, BSWM_CODE) BswM_BswNotificationInit(void);

FUNC(void, BSWM_CODE) BswM_ReadSwcDeferredPorts(void);

#define BSWM_STOP_SEC_CODE
#include "BswM_MemMap.h"

#endif /* BSWM_SWC_H */
/*========================= END OF FILE BswM_Swc.h============================*/
