/******************************************************************************
 *
 *                          Copyright 2021 Siemens
 *                           All Rights Reserved
 *
 * THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY INFORMATION WHICH IS
 * THE PROPERTY OF SIEMENS OR ITS LICENSORS AND IS SUBJECT TO LICENSE TERMS.
 *
 ******************************************************************************
 *
 * This file is automatically generated by VSC.
 * Do not edit manually!
 * VSC Version:  2.6.8
 * BswMPlugin:   com.mentor.bsw.bswm.generator 5.18.0
 *
 ******************************************************************************
 *
 * Module:       BswM
 *
 * File Name:    BswM_Version.h
 *
 * Description:  AUTOSAR and SOFTWARE Version details.
 *
 * Requirements:
 *
 ******************************************************************************/

#ifndef BSWM_VERSION_H
#define BSWM_VERSION_H

/*=============================== INCLUSIONS =================================*/

#include "Std_Types.h"

/*============================ TYPE DEFINITIONS ==============================*/

/*========================= PUBLISHED INFORMATION ============================*/

/**
 * Vendor ID as defined in vendor list (31 for Mentor Graphics)
 */
#define BSWM_VENDOR_ID                          ((uint16) 31U)

/**
 * Module ID as defined in AUTOSAR_BasicSoftwareModules.pdf
 */
#define BSWM_MODULE_ID                          ((uint16) 42U)

/**
 * Instance ID as defined in AUTOSAR_BasicSoftwareModules.pdf
 */
#define BSWM_INSTANCE_ID                        ((uint8)   1U)

/*============================== VERSION INFO ================================*/

/**
 * Major version number of AUTOSAR Release on which the
 * appropriate implementation is based on.
 */
#define BSWM_AR_RELEASE_MAJOR_VERSION           (4U)

/**
 * Minor version number of AUTOSAR Release on which the
 * appropriate implementation is based on.
 */
#define BSWM_AR_RELEASE_MINOR_VERSION           (2U)

/**
 * Patch level version number of AUTOSAR Release on which the
 * appropriate implementation is based on.
 */
#define BSWM_AR_RELEASE_REVISION_VERSION        (2U)


/**
 * Major version number of the vendor specific implementation of the module.
 * The numbering is vendor specific.
 */
#define BSWM_SW_MAJOR_VERSION                   (5U)

/**
 * Minor version number of the vendor specific implementation of the module.
 * The numbering is vendor specific.
 */
#define BSWM_SW_MINOR_VERSION                   (18U)

/**
 * Patch version number of the vendor specific implementation of the module.
 * The numbering is vendor specific.
 */
#define BSWM_SW_PATCH_VERSION                   (0U)


/*============================ MACRO DEFINITIONS =============================*/

/*===================== EXTERNAL VARIABLE DECLARATIONS =======================*/

/*===================== EXTERNAL FUNCTION DECLARATIONS =======================*/

#endif /* BSWM_VERSION_H */
/*======================= END OF FILE BswM_Version.h =========================*/
