/******************************************************************************
 *
 *                          Copyright 2021 Siemens
 *                           All Rights Reserved
 *
 * THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY INFORMATION WHICH IS
 * THE PROPERTY OF SIEMENS OR ITS LICENSORS AND IS SUBJECT TO LICENSE TERMS.
 *
 ******************************************************************************
 *
 * This file is automatically generated by VSC.
 * Do not edit manually!
 * VSC Version:  2.6.8
 * BswMPlugin:   com.mentor.bsw.bswm.generator 5.18.0
 *
 ******************************************************************************
 *
 * Module:       BswM
 *
 * File Name:    BswM_PBcfg.c
 *
 * Description:  Contains implementation of the the Post-Build parameters.
 *
 ******************************************************************************/

#define BSWM_INTERNAL_LCFG_SYMBOL_EXPORT_NEEDED
#define BSWM_USER_INCLUDE_FILE_EXPORT_NEEDED

/*=============================== INCLUSIONS =================================*/

#include "BswM_Private.h"

/*============================== VERSION CHECK ===============================*/

#if((BSWM_PBCFG_SW_MAJOR_VERSION != BSWM_SW_MAJOR_VERSION) || \
    (BSWM_PBCFG_SW_MINOR_VERSION != BSWM_SW_MINOR_VERSION) || \
    (BSWM_PBCFG_SW_PATCH_VERSION != BSWM_SW_PATCH_VERSION))
#   error "The software version of the BSWM_PBCFG header file does not match the expected version!"
#endif

/*============================ MACRO DEFINITIONS =============================*/

/*====================== INTERNAL VARIABLE DEFINITIONS =======================*/

#define BSWM_START_SEC_POSTBUILD_CONST_UNSPECIFIED
#include "BswM_MemMap.h"

/* Pust-Build to Pre-Compile Hash Value to be used in configuration consistency check */
static CONST(uint32, BSWM_CONFIG_DATA) PBtoPCHashValue = (uint32)2440608994U;

/* Pust-Build to Link-Time Hash Value to be used in configuration consistency check */
static CONST(uint32, BSWM_CONFIG_DATA) PBtoLTHashValue = (uint32)969433478U;

#define BSWM_STOP_SEC_POSTBUILD_CONST_UNSPECIFIED
#include "BswM_MemMap.h"

#define BSWM_START_SEC_POSTBUILD_CONST_UNSPECIFIED
#include "BswM_MemMap.h"








/* ActionListItem structures of BswM_AL_StartupOne */
static CONST(BswM_ActionListItemType, BSWM_CONFIG_DATA) BswM_AL_AL_StartupOne[] =
{
    /* type, elementIndex, parameterIndex, hasAbortOnFail, */
    { BSWM_ACTION, 0, 0, FALSE}  /* Action_StartupOne */
};

/* ActionListItem structures of BswM_AL_StartupTwo */
static CONST(BswM_ActionListItemType, BSWM_CONFIG_DATA) BswM_AL_AL_StartupTwo[] =
{
    /* type, elementIndex, parameterIndex, hasAbortOnFail, */
    { BSWM_ACTION, 1, 0, FALSE}, /* Action_RteStart */
    { BSWM_ACTION, 2, 0, FALSE}  /* Action_Run */
};

/* ActionList Structure */
static CONST(BswM_ActionListType, BSWM_CONFIG_DATA) BswM_AllActionLists[] =
{
    /* ptrActionListItems, executionType, itemsTotalCount */
    { BswM_AL_AL_StartupOne, BSWM_CONDITION, 1},
    { BswM_AL_AL_StartupTwo, BSWM_CONDITION, 2}
};

/* Post-Build properties of each Rule */
static CONST(BswM_RulePBPropertiesType, BSWM_CONFIG_DATA) BswM_RulePBProperties[] =
{
    /* ptrTrueActionList, ptrFalseActionList */
    { &BswM_AllActionLists[0], NULL_PTR, TRUE},
    { &BswM_AllActionLists[1], NULL_PTR, TRUE}
};




#define BSWM_STOP_SEC_POSTBUILD_CONST_UNSPECIFIED
#include "BswM_MemMap.h"


/*====================== INTERNAL FUNCTION DECLARATIONS ======================*/

/*====================== EXTERNAL VARIABLE DEFINITIONS =======================*/

#define BSWM_START_SEC_POSTBUILD_CONST_UNSPECIFIED
#include "BswM_MemMap.h"

/* Main Post-Build configuration structure */
CONST(BswM_ConfigType, BSWM_CONFIG_DATA) BswMConfig =
{


    /* Pointer to the array containing PB properties of each BswMRule */
    BswM_RulePBProperties,
    /* Pointer to the array containing PB properties of each BswMActionList */
    BswM_AllActionLists,
    /* Pointer to the PC Hash Value */
    &PBtoPCHashValue,
    /* Pointer to the LT Hash Value */
    &PBtoLTHashValue,
};

#define BSWM_STOP_SEC_POSTBUILD_CONST_UNSPECIFIED
#include "BswM_MemMap.h"


/*====================== EXTERNAL FUNCTION DEFINITIONS =======================*/

/*====================== INTERNAL FUNCTION DEFINITIONS =======================*/

/*========================= END OF FILE BswM_PBcfg.c =========================*/
