/******************************************************************************
 *
 *                          Copyright 2021 Siemens
 *                           All Rights Reserved
 *
 * THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY INFORMATION WHICH IS
 * THE PROPERTY OF SIEMENS OR ITS LICENSORS AND IS SUBJECT TO LICENSE TERMS.
 *
 ******************************************************************************
 *
 * This file is automatically generated by VSC.
 * Do not edit manually!
 * VSC Version:  2.6.8
 * BswMPlugin:   com.mentor.bsw.bswm.generator 5.18.0
 *
 ******************************************************************************
 *
 * Module:      BswM
 *
 * File Name:   BswM_Private.h
 *
 * Description: Declaration of internal functions.
 *              Do NOT include from external code!
 *
 ******************************************************************************/

#ifndef BSWM_PRIVATE_H
#define BSWM_PRIVATE_H

/*=============================== INCLUSIONS =================================*/

#include "BswM_Private_Types.h"

#include "BswM.h"

/* Contains only generated Link-Time API prototypes,
 * so can be included into a static PC source file! */
#include "BswM_GeneratedAPIs.h"

#include "SchM_BswM.h"

#include "Rte_BswM.h"

/*============================ TYPE DEFINITIONS ==============================*/

/*============================= VERSION CHECK ================================*/

/** Version checks for local module files *************************************/

/* SW version check: BswM static source <--> BswM generated PC source */
#if((BSWM_CFG_SW_MAJOR_VERSION != BSWM_SW_MAJOR_VERSION) || \
    (BSWM_CFG_SW_MINOR_VERSION != BSWM_SW_MINOR_VERSION) || \
    (BSWM_CFG_SW_PATCH_VERSION != BSWM_SW_PATCH_VERSION))
#   error "Mismatch in Software Version with BswM_Cfg.h!"
#endif


/** Version checks for standard header files **********************************/

/* AR version check: BswM module <--> Standard Types */
#if((STD_AR_RELEASE_MAJOR_VERSION != BSWM_AR_RELEASE_MAJOR_VERSION) || \
    (STD_AR_RELEASE_MINOR_VERSION != BSWM_AR_RELEASE_MINOR_VERSION))
#   error "Mismatch in AUTOSAR Version with Std_Types.h!"
#endif

/* AR version check: BswM module <--> COM Stack Types */
#if((COMTYPE_AR_RELEASE_MAJOR_VERSION != BSWM_AR_RELEASE_MAJOR_VERSION) || \
    (COMTYPE_AR_RELEASE_MINOR_VERSION != BSWM_AR_RELEASE_MINOR_VERSION))
#   error "Mismatch in AUTOSAR Version with ComStack_Types.h!"
#endif


/** Version checks for foreign module files - [VSTAR_BSWM-00136]  *************/

/* AR version check: BswM module <--> SchM module */
#if((SCHM_AR_RELEASE_MAJOR_VERSION != BSWM_AR_RELEASE_MAJOR_VERSION) || \
    (SCHM_AR_RELEASE_MINOR_VERSION != BSWM_AR_RELEASE_MINOR_VERSION))
#error "Mismatch in AUTOSAR Release Version with SchM_BswM.h!"
#endif

/* AR version check: BswM module <--> Rte module */
#if((RTE_AR_RELEASE_MAJOR_VERSION != BSWM_AR_RELEASE_MAJOR_VERSION) || \
    (RTE_AR_RELEASE_MINOR_VERSION != BSWM_AR_RELEASE_MINOR_VERSION))
#error "Mismatch in AUTOSAR Release Version with Rte_BswM!"
#endif


/*============================ MACRO DEFINITIONS =============================*/

/** Common constants **********************************************************/

/**
 * Internal symbols for indication of BswM Initialization Status.
 */
#define BSWM_INIT                       (TRUE)
#define BSWM_UNINIT                     (FALSE)

/**
 * Internal symbols for indication whether a deferred rule shall be
 * processed in the next Main Function or not.
 */
#define BSWM_IN_MAIN                    (TRUE)
#define BSWM_NOT_MAIN                   (FALSE)

/**
 * Internal symbols for indication of Rule Processing Type.
 */
#define BSWM_DEFERRED                   (TRUE)
#define BSWM_IMMEDIATE                  (FALSE)

/**
 * Internal symbols for indication of Rule State.
 */
#define BSWM_FALSE                      ((uint8) 0U)
#define BSWM_TRUE                       ((uint8) 1U)
#define BSWM_UNDEFINED                  ((uint8) 2U)

/**
 * Internal symbols for indication of PduR Routing Path Group Status.
 */
#define BSWM_PDUR_DISABLE               ((uint8) 0U)
#define BSWM_PDUR_ENABLE                ((uint8) 1U)

/**
 * Internal symbols for indication of an Event State.
 *  - BSWM_EVENT_IS_CLEARED: Event is not yet indicated
 *  - BSWM_EVENT_IS_SET: Event is indicated, but can be cleared with BswMClearEventRequest() Action!
 */
#define BSWM_EVENT_IS_CLEARED           ((BswM_EventStateType) 0U)
#define BSWM_EVENT_IS_SET               ((BswM_EventStateType) 1U)


/** Utility macros ************************************************************/

/* KW MISRA.DEFINE.FUNC VIOLATIONS 3 BEGIN Function-like macro used for increased efficiency, readability */

/* Macro for reporting to the DET module */
#define BSWM_CALL_DET(_apiId, _errId)

/* KW MISRA.DEFINE.FUNC VIOLATIONS END */

/*===================== EXTERNAL VARIABLE DECLARATIONS =======================*/

/** Extern declarations for accessing Link-Time Symbols ***********************/

#define BSWM_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "BswM_MemMap.h"

/* Public CRC32 hash values for link time and post build checks */
extern CONST(uint32, BSWM_CONST) BswM_LTHashValue;
extern CONST(uint32, BSWM_CONST) BswM_LTtoPCHashValue;

#define BSWM_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "BswM_MemMap.h"


#define BSWM_START_SEC_VAR_INIT_8
#include "BswM_MemMap.h"

/* Initialization Status of the BswM module */
extern VAR(boolean, BSWM_VAR) BswM_InitStatus;

#define BSWM_STOP_SEC_VAR_INIT_8
#include "BswM_MemMap.h"


#define BSWM_START_SEC_VAR_NO_INIT_UNSPECIFIED
#include "BswM_MemMap.h"

/* Pointer to the actual Post-Build configuration structure of the BswM */
extern P2CONST(BswM_ConfigType, BSWM_VAR, BSWM_CONFIG_DATA) BswM_PBcfgPtr;

#define BSWM_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
#include "BswM_MemMap.h"


#define BSWM_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "BswM_MemMap.h"

/* Structure containing the Lookup Table Size of each Mode Request Source */
extern CONST(BswM_LookupSizeStructType, BSWM_CONST) BswM_LookupSize;

#define BSWM_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "BswM_MemMap.h"


/*===================== EXTERNAL FUNCTION DECLARATIONS =======================*/


#endif /* BSWM_PRIVATE_H */
/*======================= END OF FILE BswM_Private.h =========================*/
