/******************************************************************************
 *
 *                          Copyright 2021 Siemens
 *                           All Rights Reserved
 *
 * THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY INFORMATION WHICH IS
 * THE PROPERTY OF SIEMENS OR ITS LICENSORS AND IS SUBJECT TO LICENSE TERMS.
 *
 ******************************************************************************
 *
 * This file is automatically generated by VSC.
 * Do not edit manually!
 * VSC Version:  2.6.8
 * BswMPlugin:   com.mentor.bsw.bswm.generator 5.18.0
 *
 ******************************************************************************
 *
 * Module:       BswM
 *
 * File Name:    BswM_GeneratedAPIs.h
 *
 * Description:  Contains declaration of internally used, generated APIs.
 *
 ******************************************************************************/

#ifndef BSWM_GENERATEDAPIS_H
#define BSWM_GENERATEDAPIS_H

/*=============================== INCLUSIONS =================================*/

#include "BswM_Private_Types.h"

/*============================== VERSION INFO ================================*/

#define BSWM_GENERATEDAPIS_SW_MAJOR_VERSION    (5U)
#define BSWM_GENERATEDAPIS_SW_MINOR_VERSION    (18U)
#define BSWM_GENERATEDAPIS_SW_PATCH_VERSION    (0U)

/*============================ TYPE DEFINITIONS ==============================*/

/*============================ MACRO DEFINITIONS =============================*/

/*===================== EXTERNAL VARIABLE DECLARATIONS =======================*/

/*===================== EXTERNAL FUNCTION DECLARATIONS =======================*/

#define BSWM_START_SEC_CODE
#include "BswM_MemMap.h"

/******************************************************************************
 * Function name: BswM_GeneratedInit
 * Description:   Service to perform the functionality of the BswM_Init() API.
 ******************************************************************************/
FUNC(void, BSWM_CODE) BswM_GeneratedInit
(
    void
);

/******************************************************************************
 * Function name: BswM_EcuMRuleEvaluation
 * Description:   Generated function called by a BswM API to evaluate the ModeRequest.
 ******************************************************************************/
FUNC(void, BSWM_CODE) BswM_EcuMRuleEvaluation
(
    VAR(EcuM_StateType, AUTOMATIC) RequestedMode
);

/******************************************************************************
 * Function name: BswM_EcuMWakeupRuleEvaluation
 * Description:   Generated function called by a BswM API to evaluate the ModeRequest.
 ******************************************************************************/
FUNC(void, BSWM_CODE) BswM_EcuMWakeupRuleEvaluation
(
    VAR(EcuM_WakeupSourceType, AUTOMATIC) RequestSource,
    VAR(EcuM_WakeupStatusType, AUTOMATIC) RequestedMode
);

#define BSWM_STOP_SEC_CODE
#include "BswM_MemMap.h"

#endif /* BSWM_GENERATEDAPIS_H */
/*==================== END OF FILE BswM_GeneratedAPIs.h ======================*/
