/******************************************************************************
 *
 *                          Copyright 2021 Siemens
 *                           All Rights Reserved
 *
 * THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY INFORMATION WHICH IS
 * THE PROPERTY OF SIEMENS OR ITS LICENSORS AND IS SUBJECT TO LICENSE TERMS.
 *
 ******************************************************************************
 *
 * This file is automatically generated by VSC.
 * Do not edit manually!
 * VSC Version:  2.6.8
 * BswMPlugin:   com.mentor.bsw.bswm.generator 5.18.0
 *
 ******************************************************************************
 *
 * Module:       BswM
 *
 * File Name:    BswM_Cfg.h
 *
 * Description:  Contains the Pre-Compile configuration parameters of the BswM
 *               module for enabling/disabling some functionality.
 *
 ******************************************************************************/

#ifndef BSWM_CFG_H
#define BSWM_CFG_H

/*=============================== INCLUSIONS =================================*/

#include "Std_Types.h"

#include "Rte_BswM_Type.h"

#include "SchM_BswM_Type.h"

#ifdef BSWM_USER_INCLUDE_FILE_EXPORT_NEEDED
/* BswMUserIncludeFiles */
#   include "Os.h"
#   include "EcuM.h"
#   include "Rte_Main.h"
#endif

/*============================== VERSION INFO ================================*/

#define BSWM_CFG_SW_MAJOR_VERSION              (5U)
#define BSWM_CFG_SW_MINOR_VERSION              (18U)
#define BSWM_CFG_SW_PATCH_VERSION              (0U)

/*============================ TYPE DEFINITIONS ==============================*/

/* Type definition for indexing Rules. */
typedef uint8 BswM_RuleIndexType;

/* Type definition for indexing ModeRequestPort */
typedef uint8 BswM_PortIndexType;

/*============================ MACRO DEFINITIONS =============================*/

/** General Pre-Processor switches ********************************************/

/**
 * Pre-Processor switch to enable/disable development error detection and reporting.
 */
#define BSWM_DEV_ERROR_DETECT                  (STD_OFF)

/**
 * Pre-Processor switch to enable/disable the existence of the BswM_GetVersionInfo() API.
 */
#define BSWM_VERSION_INFO_API                  (STD_ON)

/**
 * Pre-Processor switch to enable-disable the version check for foreign modules.
 */
#define BSWM_VERSION_CHECK_FOREIGN_MODULE      (STD_ON)

/**
 * Pre-Processor switch to indicate whether it is a single or multi partition configuration.
 */
#define BSWM_MULTI_PARTITION_ENABLED           (STD_OFF)

/**
 * Pre-Processor switch to enable-disable the support of the Vendor Specific COM Stack Partitioning Concept.
 */
#define BSWM_COM_STACK_PARTITIONING_SUPPORT    (STD_OFF)

/**
 * Pre-Processor switch to indicate whether there is any BswMReportFailToDem reference is configured.
 */
#define BSWM_IS_DEM_REPORTING_USED             (STD_OFF)


/** Pre-Processor switches to enable-disable Mode Request Source types ********/

#define BSWM_CANSM_ENABLED                     (STD_OFF)
#define BSWM_COMM_ENABLED                      (STD_OFF)
#define BSWM_DCM_ENABLED                       (STD_OFF)
#define BSWM_ECUM_ENABLED                      (STD_ON)
#define BSWM_ETHIF_ENABLED                     (STD_OFF)
#define BSWM_ETHSM_ENABLED                     (STD_OFF)
#define BSWM_FRSM_ENABLED                      (STD_OFF)
#define BSWM_GENERIC_REQUEST_ENABLED           (STD_OFF)
#define BSWM_LINSM_ENABLED                     (STD_OFF)
#define BSWM_LINTP_ENABLED                     (STD_OFF)
#define BSWM_NVM_ENABLED                       (STD_OFF)
#define BSWM_SCHM_ENABLED                      (STD_ON)
#define BSWM_SD_ENABLED                        (STD_OFF)
#define BSWM_WDGM_ENABLED                      (STD_OFF)


/** Pre-Processor switches to enable-disable Action types ********************/

#define BSWM_COM_ACTION_PRESENT                (STD_OFF)
#define BSWM_COMM_ACTION_PRESENT               (STD_OFF)
#define BSWM_ECUM_ACTION_PRESENT               (STD_OFF)
#define BSWM_ETHIF_ACTION_PRESENT              (STD_OFF)
#define BSWM_LINSM_ACTION_PRESENT              (STD_OFF)
#define BSWM_NM_ACTION_PRESENT                 (STD_OFF)
#define BSWM_PDUR_ACTION_PRESENT               (STD_OFF)
#define BSWM_SD_ACTION_PRESENT                 (STD_OFF)


/** Internally Used Macro Definitions *****************************************/

#define BSWM_NUMBER_OF_PARTITIONS              ((uint8)1)
#define BSWM_NUMBER_OF_SUPPORTED_MRS_TYPES     ((uint8)24)
#define BSWM_NUMBER_OF_SUPPORTED_ACTION_TYPES  ((uint8)23)


/** Hash Values ***************************************************************/

/**
 * Pre-Compile Hash Value.
 */
#define BSWM_PC_HASH_VALUE ((uint32)2440608994U)

/*===================== EXTERNAL VARIABLE DECLARATIONS =======================*/

/*===================== EXTERNAL FUNCTION DECLARATIONS =======================*/

#endif /* BSWM_CFG_H */
/*======================== END OF FILE BswM_Cfg.h ============================*/
