/******************************************************************************
 *
 *                          Copyright 2021 Siemens
 *                           All Rights Reserved
 *
 * THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY INFORMATION WHICH IS
 * THE PROPERTY OF SIEMENS OR ITS LICENSORS AND IS SUBJECT TO LICENSE TERMS.
 *
 ******************************************************************************
 *
 * This file is automatically generated by VSC.
 * Do not edit manually!
 * VSC Version:  2.6.8
 * BswMPlugin:   com.mentor.bsw.bswm.generator 5.18.0
 *
 ******************************************************************************
 *
 * Module:       BswM
 *
 * File Name:    BswM.c
 *
 * Description:  Contains implementation of public API functions.
 *
 * Requirements: [SWS_BSWM-00218.v2] File structure.
 *
 ******************************************************************************/

#define VSTAR_BSW_STATIC_SOURCE
#define BSWM_USER_INCLUDE_FILE_EXPORT_NEEDED

/*=============================== INCLUSIONS =================================*/

#include "BswM_Private.h"

/*============================ TYPE DEFINITIONS ==============================*/

/*============================ MACRO DEFINITIONS =============================*/

/*====================== INTERNAL VARIABLE DEFINITIONS =======================*/

/*====================== INTERNAL FUNCTION DECLARATIONS ======================*/

/*====================== EXTERNAL VARIABLE DEFINITIONS =======================*/

/*====================== EXTERNAL FUNCTION DEFINITIONS =======================*/

#define BSWM_START_SEC_CODE
#include "BswM_MemMap.h"

/******************************************************************************
 * Function name: BswM_Deinit()
 * Description:   De-Initializes the BSW Mode Manager.
 * Requirements:  [SWS_BSWM-00119] [SWS_BSWM-00120]
 ******************************************************************************/
FUNC(void, BSWM_CODE) BswM_Deinit(void)
{
    BswM_InitStatus = BSWM_UNINIT;
}

/******************************************************************************
 * Function name: BswM_Init()
 * Description:   Initializes the BSW Mode Manager.
 * Requirements:  [SWS_BSWM-00002] [SWS_BSWM-00043] [SWS_BSWM-00044] [SWS_BSWM-00118]
 ******************************************************************************/
FUNC(void, BSWM_CODE) BswM_Init
(
    P2CONST(BswM_ConfigType, AUTOMATIC, BSWM_CONST) ConfigPtr
)
{

    if(E_NOT_OK == BswM_ConsistencyCheck(ConfigPtr))
    {
        /* Invalid configuration pointer, do NOT initialize! */
        if(ConfigPtr == NULL_PTR)
        {
            /* [VSTAR_BSWM-00088] NULL pointer instead of a valid configuration. */
            BSWM_CALL_DET(BSWM_INIT_API_ID, BSWM_E_NULL_POINTER);
        }
        else
        {
            /* [SWS_BSWM-00045] Invalid configuration due Hash mismatch. */
            BSWM_CALL_DET(BSWM_INIT_API_ID, BSWM_E_PARAM_CONFIG);
        }
    }
    else
    {
        BswM_PBcfgPtr = ConfigPtr;
        BswM_GeneratedInit();
    }
}


/******************************************************************************
 * Function name: BswM_ConsistencyCheck()
 * Description:   Function called by EcuM to check consistency of the given BswM
 *                Post-Build configuration.
 * Requirements:
 ******************************************************************************/
FUNC(Std_ReturnType, BSWM_CODE) BswM_ConsistencyCheck
(
    P2CONST(BswM_ConfigType, AUTOMATIC, BSWM_CONST) ConfigPtr
)
{
    VAR(Std_ReturnType, AUTOMATIC) retVal;

    if( (ConfigPtr != NULL_PTR) &&
        (BSWM_PC_HASH_VALUE == BswM_LTtoPCHashValue) &&
        (BSWM_PC_HASH_VALUE == *(ConfigPtr->ptrPBtoPCHashValue)) &&
        (BswM_LTHashValue == *(ConfigPtr->ptrPBtoLTHashValue)))
    {
        retVal = E_OK;
    }
    else
    {
        retVal = E_NOT_OK;
    }

    return retVal;
}


/******************************************************************************
 * Function name: BswM_GetVersionInfo()
 * Description:   Returns the version information of this module.
 * Requirements:  [SWS_BSWM-00003]
 ******************************************************************************/
FUNC(void, BSWM_CODE) BswM_GetVersionInfo
(
    P2VAR(Std_VersionInfoType, AUTOMATIC, BSWM_APPL_DATA) VersionInfo
)
{
    if(VersionInfo == NULL_PTR)
    {
        /* [VSTAR_BSWM-00139] NULL pointer error. */
        BSWM_CALL_DET(BSWM_GETVERSIONINFO_API_ID, BSWM_E_NULL_POINTER);
    }
    else
    {
        /* [VSTAR_BSWM-00004] Return version information. */
        VersionInfo->moduleID = BSWM_MODULE_ID;
        VersionInfo->vendorID = BSWM_VENDOR_ID;
        VersionInfo->sw_major_version = (uint8) BSWM_SW_MAJOR_VERSION;
        VersionInfo->sw_minor_version = (uint8) BSWM_SW_MINOR_VERSION;
        VersionInfo->sw_patch_version = (uint8) BSWM_SW_PATCH_VERSION;
    }
}


/** Implementation of APIs related to ModeRequestPorts ************************/


/******************************************************************************
 * Function name: BswM_EcuM_CurrentState()
 * Description:   API representation of the 'BswMEcuMIndication' ModeRequestSource.
 * Requirements:  [SWS_BSWM-00056] [VSTAR_BSWM-90941-01] [VSTAR_BSWM-90056]
 ******************************************************************************/
FUNC(void, BSWM_CODE) BswM_EcuM_CurrentState
(
    VAR(EcuM_StateType, AUTOMATIC) CurrentState
)
{
    if(BswM_InitStatus != BSWM_INIT)
    {
        /* [SWS_BSWM-00084] BswM is not yet initialized --> Abort request and report to DET! */
        BSWM_CALL_DET(BSWM_ECUM_API_ID, BSWM_E_NO_INIT);
    }
    else
    {
        if(BswM_LookupSize.EcuM > 0U)
        {
            BswM_EcuMRuleEvaluation(CurrentState);
        }
    }
}


/******************************************************************************
 * Function name: BswM_EcuM_CurrentWakeup()
 * Description:   API representation of the 'BswMEcuMWakeupSource' ModeRequestSource.
 * Requirements:  [SWS_BSWM-00131] [VSTAR_BSWM-90941-01] [VSTAR_BSWM-90131]
 ******************************************************************************/
FUNC(void, BSWM_CODE) BswM_EcuM_CurrentWakeup
(
    VAR(EcuM_WakeupSourceType, AUTOMATIC) source,
    VAR(EcuM_WakeupStatusType, AUTOMATIC) state
)
{
    if(BswM_InitStatus != BSWM_INIT)
    {
        /* [SWS_BSWM-00132] BswM is not yet initialized --> Abort request and report to DET! */
        BSWM_CALL_DET(BSWM_ECUMWAKEUP_API_ID, BSWM_E_NO_INIT);
    }
    else
    {
        if(BswM_LookupSize.EcuMWakeup > 0U)
        {
            BswM_EcuMWakeupRuleEvaluation(source, state);
        }
    }
}


#define BSWM_STOP_SEC_CODE
#include "BswM_MemMap.h"

/*====================== INTERNAL FUNCTION DEFINITIONS =======================*/

/*=========================== END OF FILE BswM.c =============================*/
