/******************************************************************************
 *
 *                          Copyright 2021 Siemens
 *                           All Rights Reserved
 *
 * THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY INFORMATION WHICH IS
 * THE PROPERTY OF SIEMENS OR ITS LICENSORS AND IS SUBJECT TO LICENSE TERMS.
 *
 ******************************************************************************
 *
 * This file is automatically generated by VSC.
 * Do not edit manually!
 * VSC Version:  2.6.8
 * BswMPlugin:   com.mentor.bsw.bswm.generator 5.18.0
 *
 ******************************************************************************
 *
 * Module:       BswM
 *
 * File Name:    BswM_Lcfg.c
 *
 * Description:  Contains implementation of the the Link-Time parameters.
 *
 ******************************************************************************/

#define VSTAR_BSW_LCFG_SOURCE
#define BSWM_INTERNAL_LCFG_SYMBOL_EXPORT_NEEDED
#define BSWM_USER_INCLUDE_FILE_EXPORT_NEEDED

/*=============================== INCLUSIONS =================================*/

#include "BswM_Private.h"

/*============================== VERSION CHECK ===============================*/

#if((BSWM_LCFG_SW_MAJOR_VERSION != BSWM_SW_MAJOR_VERSION) || \
    (BSWM_LCFG_SW_MINOR_VERSION != BSWM_SW_MINOR_VERSION) || \
    (BSWM_LCFG_SW_PATCH_VERSION != BSWM_SW_PATCH_VERSION))
#   error "The software version of the BSWM_LCFG header file does not match the expected version!"
#endif

/*============================ MACRO DEFINITIONS =============================*/

/*====================== INTERNAL VARIABLE DEFINITIONS =======================*/

/*====================== INTERNAL FUNCTION DECLARATIONS ======================*/

/*====================== EXTERNAL VARIABLE DEFINITIONS =======================*/

#define BSWM_START_SEC_VAR_INIT_8
#include "BswM_MemMap.h"

VAR(boolean, BSWM_VAR) BswM_InitStatus = BSWM_UNINIT;

#define BSWM_STOP_SEC_VAR_INIT_8
#include "BswM_MemMap.h"


#define BSWM_START_SEC_VAR_NO_INIT_UNSPECIFIED
#include "BswM_MemMap.h"

P2CONST(BswM_ConfigType, BSWM_VAR, BSWM_CONFIG_DATA) BswM_PBcfgPtr;


VAR(BswM_GlobalRuleEvaluationType, BSWM_VAR_NO_INIT) BswM_GlobalRuleEvaluation[2];


#define BSWM_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
#include "BswM_MemMap.h"


#define BSWM_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "BswM_MemMap.h"

CONST(BswM_RuleIndexType, BSWM_CONST) BswM_TotalRuleCount = (BswM_RuleIndexType)2U;

CONST(BswM_LookupSizeStructType, BSWM_CONST) BswM_LookupSize =
{
    0, /* Total Number of Lookup Table Entries related to BswMEcuMIndication Mode Request Source type */
    0, /* Total Number of Lookup Table Entries related to BswMEcuMWakeupSource Mode Request Source type */
};

CONST(BswM_CurrentStateSizeStructType, BSWM_CONST) BswM_CurrentStateSize =
{
    0, /* Total Number of BswMEcuMIndication Mode Request Source type Mode Request Ports */
    0, /* Total Number of BswMEcuMWakeupSource Mode Request Source type Mode Request Ports */
};

/* [VSTAR_BSWM-90666] Rules are listed in ascending alphabetical order! */
CONST(BswM_RulePropertiesType, BSWM_CONST) BswM_RuleProperties[2] = {
    /* ruleFunction, initState, inMainDefaultValue */
    /* 0 */ { &BswM_Rule_StartupOne_SingleCore, BSWM_UNDEFINED, BSWM_IN_MAIN },
    /* 1 */ { &BswM_Rule_StartupTwo_SingleCore, BSWM_UNDEFINED, BSWM_IN_MAIN }
};


/*
 * The following Lookup Tables hold each Rule -- ModeRequestPort pair
 * This is necessary because a Rule uses 1..* ModeRequestPorts and a ModeRequestPort can be used by 0..* Rules
 */




CONST(BswM_ActionFuncPtrType, BSWM_CONST) BswM_ActionsArray[3] =
{
    &BswM_SchMSwitch_Action_StartupOne,
    &BswM_UserCallout_Action_RteStart,
    &BswM_SchMSwitch_Action_Run
};


#define BSWM_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "BswM_MemMap.h"


#define BSWM_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "BswM_MemMap.h"

/* Public CRC32 hash values for link time and post build checks */
CONST(uint32, BSWM_CONST) BswM_LTtoPCHashValue = (uint32)2440608994U;
CONST(uint32, BSWM_CONST) BswM_LTHashValue = (uint32)969433478U;

#define BSWM_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "BswM_MemMap.h"

/*====================== EXTERNAL FUNCTION DEFINITIONS =======================*/

/*====================== INTERNAL FUNCTION DEFINITIONS =======================*/

/*========================= END OF FILE BswM_Lcfg.c ==========================*/
