/******************************************************************************
 *
 *                          Copyright 2021 Siemens
 *                           All Rights Reserved
 *
 * THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY INFORMATION WHICH IS
 * THE PROPERTY OF SIEMENS OR ITS LICENSORS AND IS SUBJECT TO LICENSE TERMS.
 *
 ******************************************************************************
 *
 * This file is automatically generated by VSC.
 * Do not edit manually!
 * VSC Version:  2.6.8
 * BswMPlugin:   com.mentor.bsw.bswm.generator 5.18.0
 *
 ******************************************************************************
 *
 * Module:       BswM
 *
 * File Name:    BswM_EcuM.h
 *
 * Description:  Declaration of API functions used by EcuM module.
 *
 * Requirements: [SWS_BSWM-00026.v4]
 *
 ******************************************************************************/

#ifndef BSWM_ECUM_H
#define BSWM_ECUM_H

/*=============================== INCLUSIONS =================================*/

#include "BswM_Types.h"

#include "EcuM.h"

/*============================ TYPE DEFINITIONS ==============================*/

/*============================= VERSION CHECK ================================*/

/* AR version check: BswM module <--> EcuM module */
#if((ECUM_AR_RELEASE_MAJOR_VERSION != BSWM_AR_RELEASE_MAJOR_VERSION) || \
    (ECUM_AR_RELEASE_MINOR_VERSION != BSWM_AR_RELEASE_MINOR_VERSION))
#error "Mismatch in AUTOSAR Release Version with EcuM.h!"
#endif

/*============================ MACRO DEFINITIONS =============================*/

/*===================== EXTERNAL VARIABLE DECLARATIONS =======================*/

/*===================== EXTERNAL FUNCTION DECLARATIONS =======================*/

#define BSWM_START_SEC_CODE
#include "BswM_MemMap.h"

FUNC(void, BSWM_CODE) BswM_EcuM_CurrentState
(
    VAR(EcuM_StateType, AUTOMATIC) CurrentState
);

FUNC(void, BSWM_CODE) BswM_EcuM_CurrentWakeup
(
    VAR(EcuM_WakeupSourceType, AUTOMATIC) source,
    VAR(EcuM_WakeupStatusType, AUTOMATIC) state
);

#define BSWM_STOP_SEC_CODE
#include "BswM_MemMap.h"


#endif /* BSWM_ECUM_H */
/*========================= END OF FILE BswM_EcuM.h ==========================*/
