/******************************************************************************
 *
 *                          Copyright 2021 Siemens
 *                           All Rights Reserved
 *
 * THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY INFORMATION WHICH IS
 * THE PROPERTY OF SIEMENS OR ITS LICENSORS AND IS SUBJECT TO LICENSE TERMS.
 *
 ******************************************************************************
 *
 * This file is automatically generated by VSC.
 * Do not edit manually!
 * VSC Version:  2.6.8
 * BswMPlugin:   com.mentor.bsw.bswm.generator 5.18.0
 *
 ******************************************************************************
 *
 * Module:       BswM
 *
 * File Name:    BswM_Swc.c
 *
 * Description:  Contains implementation of internally used, SWC related functions.
 *
 ******************************************************************************/

#define VSTAR_BSW_LCFG_SOURCE
#define BSWM_INTERNAL_LCFG_SYMBOL_EXPORT_NEEDED
#define BSWM_USER_INCLUDE_FILE_EXPORT_NEEDED

/*=============================== INCLUSIONS =================================*/

#include "BswM_Private.h"

/*============================== VERSION CHECK ===============================*/

#if((BSWM_SWC_SW_MAJOR_VERSION != BSWM_SW_MAJOR_VERSION) || \
    (BSWM_SWC_SW_MINOR_VERSION != BSWM_SW_MINOR_VERSION) || \
    (BSWM_SWC_SW_PATCH_VERSION != BSWM_SW_PATCH_VERSION))
#   error "The software version of the BSWM_SWC header file does not match the expected version!"
#endif

/*============================ MACRO DEFINITIONS =============================*/

/*====================== INTERNAL VARIABLE DEFINITIONS =======================*/

/*====================== EXTERNAL VARIABLE DEFINITIONS =======================*/

#define BSWM_START_SEC_VAR_NO_INIT_UNSPECIFIED
#include "BswM_MemMap.h"




/* Variable holding current state of ModeRequestPort MRP_EcuMode_SingleCore */
VAR(BswM_BswNotificationCurrentStateType0, BSWM_VAR_NO_INIT) BswM_BswNotification_MRP_EcuMode_SingleCore;

#define BSWM_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
#include "BswM_MemMap.h"


/*====================== INTERNAL FUNCTION DECLARATIONS ======================*/


#define BSWM_START_SEC_CODE
#include "BswM_MemMap.h"



/*****************************************************************************
* Function name:    BswM_ReadBswNotificationDeferredPorts
* Description:      Read Deferred ModeRequestPorts of type BswNotification
*****************************************************************************/
LOCAL_INLINE FUNC(void, BSWM_CODE) BswM_ReadBswNotificationDeferredPorts(void);


/*=========================== FUNCTION DEFINITIONS ===========================*/


LOCAL_INLINE FUNC(void, BSWM_CODE) BswM_ReadBswNotificationDeferredPorts(void)
{
    /* Temporary variables for reading new value from Rte/SchM */
    VAR(Rte_ModeType_BswM_StateType, AUTOMATIC) MRP_EcuMode_SingleCore_newValue;

    /* [VSTAR_BSWM-90926-03] Read New value for 'MRP_EcuMode_SingleCore' BswMBswModeNotification MRP */
    MRP_EcuMode_SingleCore_newValue = SchM_Mode_BswM_EcuMode();
    /* Trigger Rule evalution only if the current mode of the Mode Machine Instance has changed, but transition values are ignored! */
    if ((BswM_BswNotification_MRP_EcuMode_SingleCore.value != MRP_EcuMode_SingleCore_newValue)
        && (MRP_EcuMode_SingleCore_newValue != (Rte_ModeType_BswM_StateType)RTE_TRANSITION_BswM_StateType))
    {
        /* Update current value of the ModeRequestPort */
        BswM_BswNotification_MRP_EcuMode_SingleCore.value = MRP_EcuMode_SingleCore_newValue;
        BswM_BswNotification_MRP_EcuMode_SingleCore.isValid = TRUE;
        /* Mark Rules for evaluation */
        BswM_GlobalRuleEvaluation[0].inMain = BSWM_IN_MAIN;
        BswM_GlobalRuleEvaluation[1].inMain = BSWM_IN_MAIN;
    }
}

FUNC(void, BSWM_CODE) BswM_ReadSwcDeferredPorts(void)
{
    /* [VSTAR_BSWM-90926-03] Update value of DEFERRED 'BswMBswModeNotification' type MRPs */
    BswM_ReadBswNotificationDeferredPorts();
} /* End of BswM_ReadSwcDeferredPorts */

FUNC(void, BSWM_CODE) BswM_BswNotificationInit(void)
{
    /* [SWS_BSWM-00203.v2-03] Initialize 'MRP_EcuMode_SingleCore' ModeRequestPort with the related ModeDeclarationGroup's InitialMode */
    BswM_BswNotification_MRP_EcuMode_SingleCore.value = (Rte_ModeType_BswM_StateType)RTE_MODE_BswM_StateType_BSWM_STATE_STARTUP;
    BswM_BswNotification_MRP_EcuMode_SingleCore.isValid = TRUE;

}

#define BSWM_STOP_SEC_CODE
#include "BswM_MemMap.h"

/*========================= END OF FILE BswM_Swc.c ===========================*/
