/******************************************************************************
 *
 *                          Copyright 2020 Siemens
 *                           All Rights Reserved
 *
 * THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY INFORMATION WHICH IS
 * THE PROPERTY OF SIEMENS OR ITS LICENSORS AND IS SUBJECT TO LICENSE TERMS.
 *
 ******************************************************************************
 *
 * Module:      MemMap
 *
 * File Name:   EcuM_MemMap.h
 *
 * Description: Memory mapping header file.
 *
 *              NOTE! This file is automatically generated!
 *              Do NOT edit manually!
 *
 ******************************************************************************/


/*=============================== INCLUSIONS =================================*/

/*============================ TYPE DEFINITIONS ==============================*/

/*============================== VERSION INFO ================================*/

/** General Information *******************************************************/

#ifdef MEMMAP_VENDOR_ID
  #if (MEMMAP_VENDOR_ID != 31U)
    #error "Redefinition of MEMMAP_VENDOR_ID macro with different value!"
  #endif
#else
  #define MEMMAP_VENDOR_ID                     (31U)
#endif

#ifdef MEMMAP_MODULE_ID
  #if (MEMMAP_MODULE_ID != 195U)
    #error "Redefinition of MEMMAP_MODULE_ID macro with different value!"
  #endif
#else
  #define MEMMAP_MODULE_ID                     (195U)
#endif


/** AUTOSAR Version Information ***********************************************/

#ifdef MEMMAP_AR_RELEASE_MAJOR_VERSION
  #if (MEMMAP_AR_RELEASE_MAJOR_VERSION != 4U)
    #error "Redefinition of MEMMAP_AR_RELEASE_MAJOR_VERSION macro with different value!"
  #endif
#else
  #define MEMMAP_AR_RELEASE_MAJOR_VERSION      (4U)
#endif

#ifdef MEMMAP_AR_RELEASE_MINOR_VERSION
  #if (MEMMAP_AR_RELEASE_MINOR_VERSION != 2U)
    #error "Redefinition of MEMMAP_AR_RELEASE_MINOR_VERSION macro with different value!"
  #endif
#else
  #define MEMMAP_AR_RELEASE_MINOR_VERSION      (2U)
#endif

#ifdef MEMMAP_AR_RELEASE_REVISION_VERSION
  #if (MEMMAP_AR_RELEASE_REVISION_VERSION != 2U)
    #error "Redefinition of MEMMAP_AR_RELEASE_REVISION_VERSION macro with different value!"
  #endif
#else
  #define MEMMAP_AR_RELEASE_REVISION_VERSION   (2U)
#endif


/** Software Version Information **********************************************/

#ifdef MEMMAP_SW_MAJOR_VERSION
  #if (MEMMAP_SW_MAJOR_VERSION != 3U)
    #error "Redefinition of MEMMAP_SW_MAJOR_VERSION macro with different value!"
  #endif
#else
  #define MEMMAP_SW_MAJOR_VERSION              (3U)
#endif

#ifdef MEMMAP_SW_MINOR_VERSION
  #if (MEMMAP_SW_MINOR_VERSION != 10U)
    #error "Redefinition of MEMMAP_SW_MINOR_VERSION macro with different value!"
  #endif
#else
  #define MEMMAP_SW_MINOR_VERSION              (10U)
#endif

#ifdef MEMMAP_SW_PATCH_VERSION
  #if (MEMMAP_SW_PATCH_VERSION != 2U)
    #error "Redefinition of MEMMAP_SW_PATCH_VERSION macro with different value!"
  #endif
#else
  #define MEMMAP_SW_PATCH_VERSION              (2U)
#endif


/*============================ MACRO DEFINITIONS =============================*/

#define MEMMAP_SECTION_NOT_FOUND

#if 0

/******************************************************************************/
/** ECUM BSW                                                                 **/
/******************************************************************************/

/** ECUM - CONST_32 ***********************************************************/
#elif defined ECUM_STOP_SEC_CONST_32
    #if defined ECUM_START_SEC_CONST_32
        #undef ECUM_START_SEC_CONST_32 /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef ECUM_STOP_SEC_CONST_32 /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "ECUM_STOP_SEC_CONST_32: This section has not been previously started!"
    #endif
#elif defined ECUM_START_SEC_CONST_32
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "ECUM_START_SEC_CONST_32: Another section which is previously started has not been stopped!"
    #endif

/** ECUM - CONST_UNSPECIFIED **************************************************/
#elif defined ECUM_STOP_SEC_CONST_UNSPECIFIED
    #if defined ECUM_START_SEC_CONST_UNSPECIFIED
        #undef ECUM_START_SEC_CONST_UNSPECIFIED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef ECUM_STOP_SEC_CONST_UNSPECIFIED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "ECUM_STOP_SEC_CONST_UNSPECIFIED: This section has not been previously started!"
    #endif
#elif defined ECUM_START_SEC_CONST_UNSPECIFIED
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "ECUM_START_SEC_CONST_UNSPECIFIED: Another section which is previously started has not been stopped!"
    #endif

/** ECUM - CODE ***************************************************************/
#elif defined ECUM_STOP_SEC_CODE
    #if defined ECUM_START_SEC_CODE
        #undef ECUM_START_SEC_CODE /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef ECUM_STOP_SEC_CODE /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "ECUM_STOP_SEC_CODE: This section has not been previously started!"
    #endif
#elif defined ECUM_START_SEC_CODE
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "ECUM_START_SEC_CODE: Another section which is previously started has not been stopped!"
    #endif

/** ECUM - CONFIG_DATA_UNSPECIFIED ********************************************/
#elif defined ECUM_STOP_SEC_CONFIG_DATA_UNSPECIFIED
    #if defined ECUM_START_SEC_CONFIG_DATA_UNSPECIFIED
        #undef ECUM_START_SEC_CONFIG_DATA_UNSPECIFIED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef ECUM_STOP_SEC_CONFIG_DATA_UNSPECIFIED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "ECUM_STOP_SEC_CONFIG_DATA_UNSPECIFIED: This section has not been previously started!"
    #endif
#elif defined ECUM_START_SEC_CONFIG_DATA_UNSPECIFIED
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "ECUM_START_SEC_CONFIG_DATA_UNSPECIFIED: Another section which is previously started has not been stopped!"
    #endif

/** ECUM - CONFIG_DATA_32 *****************************************************/
#elif defined ECUM_STOP_SEC_CONFIG_DATA_32
    #if defined ECUM_START_SEC_CONFIG_DATA_32
        #undef ECUM_START_SEC_CONFIG_DATA_32 /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef ECUM_STOP_SEC_CONFIG_DATA_32 /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "ECUM_STOP_SEC_CONFIG_DATA_32: This section has not been previously started!"
    #endif
#elif defined ECUM_START_SEC_CONFIG_DATA_32
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "ECUM_START_SEC_CONFIG_DATA_32: Another section which is previously started has not been stopped!"
    #endif

/** ECUM - POSTBUILD_CONFIG_UNSPECIFIED ***************************************/
#elif defined ECUM_STOP_SEC_POSTBUILD_CONFIG_UNSPECIFIED
    #if defined ECUM_START_SEC_POSTBUILD_CONFIG_UNSPECIFIED
        #undef ECUM_START_SEC_POSTBUILD_CONFIG_UNSPECIFIED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef ECUM_STOP_SEC_POSTBUILD_CONFIG_UNSPECIFIED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "ECUM_STOP_SEC_POSTBUILD_CONFIG_UNSPECIFIED: This section has not been previously started!"
    #endif
#elif defined ECUM_START_SEC_POSTBUILD_CONFIG_UNSPECIFIED
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "ECUM_START_SEC_POSTBUILD_CONFIG_UNSPECIFIED: Another section which is previously started has not been stopped!"
    #endif

/** ECUM - POSTBUILD_CONST_UNSPECIFIED ****************************************/
#elif defined ECUM_STOP_SEC_POSTBUILD_CONST_UNSPECIFIED
    #if defined ECUM_START_SEC_POSTBUILD_CONST_UNSPECIFIED
        #undef ECUM_START_SEC_POSTBUILD_CONST_UNSPECIFIED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef ECUM_STOP_SEC_POSTBUILD_CONST_UNSPECIFIED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "ECUM_STOP_SEC_POSTBUILD_CONST_UNSPECIFIED: This section has not been previously started!"
    #endif
#elif defined ECUM_START_SEC_POSTBUILD_CONST_UNSPECIFIED
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "ECUM_START_SEC_POSTBUILD_CONST_UNSPECIFIED: Another section which is previously started has not been stopped!"
    #endif

/** ECUM - POSTBUILDLOCATOR_CONST_UNSPECIFIED *********************************/
#elif defined ECUM_STOP_SEC_POSTBUILDLOCATOR_CONST_UNSPECIFIED
    #if defined ECUM_START_SEC_POSTBUILDLOCATOR_CONST_UNSPECIFIED
        #undef ECUM_START_SEC_POSTBUILDLOCATOR_CONST_UNSPECIFIED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef ECUM_STOP_SEC_POSTBUILDLOCATOR_CONST_UNSPECIFIED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "ECUM_STOP_SEC_POSTBUILDLOCATOR_CONST_UNSPECIFIED: This section has not been previously started!"
    #endif
#elif defined ECUM_START_SEC_POSTBUILDLOCATOR_CONST_UNSPECIFIED
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "ECUM_START_SEC_POSTBUILDLOCATOR_CONST_UNSPECIFIED: Another section which is previously started has not been stopped!"
    #endif

/** ECUM - VAR_CLEARED_BOOLEAN ************************************************/
#elif defined ECUM_STOP_SEC_VAR_CLEARED_BOOLEAN
    #if defined ECUM_START_SEC_VAR_CLEARED_BOOLEAN
        #undef ECUM_START_SEC_VAR_CLEARED_BOOLEAN /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef ECUM_STOP_SEC_VAR_CLEARED_BOOLEAN /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "ECUM_STOP_SEC_VAR_CLEARED_BOOLEAN: This section has not been previously started!"
    #endif
#elif defined ECUM_START_SEC_VAR_CLEARED_BOOLEAN
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "ECUM_START_SEC_VAR_CLEARED_BOOLEAN: Another section which is previously started has not been stopped!"
    #endif

/** ECUM - VAR_INIT_32 ********************************************************/
#elif defined ECUM_STOP_SEC_VAR_INIT_32
    #if defined ECUM_START_SEC_VAR_INIT_32
        #undef ECUM_START_SEC_VAR_INIT_32 /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef ECUM_STOP_SEC_VAR_INIT_32 /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "ECUM_STOP_SEC_VAR_INIT_32: This section has not been previously started!"
    #endif
#elif defined ECUM_START_SEC_VAR_INIT_32
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "ECUM_START_SEC_VAR_INIT_32: Another section which is previously started has not been stopped!"
    #endif

/** ECUM - VAR_INIT_UNSPECIFIED ***********************************************/
#elif defined ECUM_STOP_SEC_VAR_INIT_UNSPECIFIED
    #if defined ECUM_START_SEC_VAR_INIT_UNSPECIFIED
        #undef ECUM_START_SEC_VAR_INIT_UNSPECIFIED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef ECUM_STOP_SEC_VAR_INIT_UNSPECIFIED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "ECUM_STOP_SEC_VAR_INIT_UNSPECIFIED: This section has not been previously started!"
    #endif
#elif defined ECUM_START_SEC_VAR_INIT_UNSPECIFIED
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "ECUM_START_SEC_VAR_INIT_UNSPECIFIED: Another section which is previously started has not been stopped!"
    #endif

/** ECUM - VAR_POWER_ON_INIT_UNSPECIFIED **************************************/
#elif defined ECUM_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
    #if defined ECUM_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
        #undef ECUM_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef ECUM_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "ECUM_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED: This section has not been previously started!"
    #endif
#elif defined ECUM_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "ECUM_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED: Another section which is previously started has not been stopped!"
    #endif

/** ECUM - CALLOUT_CODE *******************************************************/
#elif defined ECUM_STOP_SEC_CALLOUT_CODE
    #if defined ECUM_START_SEC_CALLOUT_CODE
        #undef ECUM_START_SEC_CALLOUT_CODE /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef ECUM_STOP_SEC_CALLOUT_CODE /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "ECUM_STOP_SEC_CALLOUT_CODE: This section has not been previously started!"
    #endif
#elif defined ECUM_START_SEC_CALLOUT_CODE
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "ECUM_START_SEC_CALLOUT_CODE: Another section which is previously started has not been stopped!"
    #endif

/** ECUM - CONSISTENCY_CODE ***************************************************/
#elif defined ECUM_STOP_SEC_CONSISTENCY_CODE
    #if defined ECUM_START_SEC_CONSISTENCY_CODE
        #undef ECUM_START_SEC_CONSISTENCY_CODE /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef ECUM_STOP_SEC_CONSISTENCY_CODE /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "ECUM_STOP_SEC_CONSISTENCY_CODE: This section has not been previously started!"
    #endif
#elif defined ECUM_START_SEC_CONSISTENCY_CODE
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "ECUM_START_SEC_CONSISTENCY_CODE: Another section which is previously started has not been stopped!"
    #endif

/** ECUM - VAR_NO_INIT_UNSPECIFIED ********************************************/
#elif defined ECUM_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
    #if defined ECUM_START_SEC_VAR_NO_INIT_UNSPECIFIED
        #undef ECUM_START_SEC_VAR_NO_INIT_UNSPECIFIED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef ECUM_STOP_SEC_VAR_NO_INIT_UNSPECIFIED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "ECUM_STOP_SEC_VAR_NO_INIT_UNSPECIFIED: This section has not been previously started!"
    #endif
#elif defined ECUM_START_SEC_VAR_NO_INIT_UNSPECIFIED
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "ECUM_START_SEC_VAR_NO_INIT_UNSPECIFIED: Another section which is previously started has not been stopped!"
    #endif

/******************************************************************************/
/** EcuM SWC                                                                 **/
/******************************************************************************/

/** EcuM - CODE ***************************************************************/
#elif defined EcuM_STOP_SEC_CODE
    #if defined EcuM_START_SEC_CODE
        #undef EcuM_START_SEC_CODE /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef EcuM_STOP_SEC_CODE /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "EcuM_STOP_SEC_CODE: This section has not been previously started!"
    #endif
#elif defined EcuM_START_SEC_CODE
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "EcuM_START_SEC_CODE: Another section which is previously started has not been stopped!"
    #endif

#endif


#if defined MEMMAP_SECTION_NOT_FOUND
    #error "Section not found in EcuM_MemMap.h"
#endif

/*====================== EXTERNAL VARIABLE DECLARATIONS ======================*/

/*====================== EXTERNAL FUNCTION DECLARATIONS ======================*/

/*======================== END OF FILE EcuM_MemMap.h =========================*/

/* KW MISRA.INCGUARD VIOLATION AUTOSAR requirement to be implemented this way.
   Neither executable code nor symbols are included (only pragmas), thus this violation is
   an approved exception without side effects. */

/* KW MISRA.PRAGMA VIOLATION Each #pragma usage comes from user configuration */
