/******************************************************************************
* This file is automatically generated by VSC.
* Do not edit manually.
* VSC Version    : 2.6.8
* Plugin Version : com.mentor.bsw.os.PowerPC.MPC5607B 5.9.0
*==============================================================================
*
* Module:       Os
*
* File Name:    Os_Cfg.h
*
* Description:  This file shall contain the configuration Precompile Time parameters
*
******************************************************************************/
#ifndef OS_CFG_H
#define OS_CFG_H

/*============================== VERSION INFO ===============================*/

#define OS_CFG_H_SW_MAJOR_VERSION    (5U)
#define OS_CFG_H_SW_MINOR_VERSION    (9U)
#define OS_CFG_H_SW_PATCH_VERSION    (0U)

/*=============================== INCLUSIONS ================================*/

#include "Std_Types.h"

/*============================ TYPE DEFINITIONS =============================*/

typedef VAR(uint64, TYPEDEF) EventMaskType;

typedef VAR(uint32, TYPEDEF) Os_LockResourceType;

/*============================ MACRO DEFINITIONS ============================*/

/**********************************************
 * General Os Configuration
 *********************************************/

#define OS_AR422
#define OS_AR_MAJOR_VERSION             (4U)
#define OS_AR_MINOR_VERSION             (2U)
#define OS_AR_PATCH_VERSION             (2U)

#define OS_MEMMAP_HEADER                "Os_MemMap.h"

#define OS_CONFIG_SC1
#define OS_CONFIG_STATUS_EXTENDED
#define OS_CONFIG_USESERVICEID
#define OS_CONFIG_STACKMONITORING  /* [OS_CONF-0307-05] Requirement verified by review */
#define OS_CONFIG_INTERNAL_VALIDATIONS   /* [OS-1108-01] [OS-1109] */ /* [OS_CONF-1130-04] Requirement verified by review */
#define OS_CONFIG_INTERRUPTSERVICE_VALIDATION
#define OS_CONFIG_USE_RES_SCHEDULER
#define OS_PRIVATE_DATA_USER_READ_ACCESSIBLE           /* [OS_CONF-1186-04] Requirement verified by review */
#define OS_CONFIG_SYSTEM_MPU

#define OS_LINKTIME_GUARD               (Os_SC1_1C_E_SS___IR___590_MPC5607B_MGCGCC)
#define OS_MCU_DERIVATIVE               Os_MPC5607B /* MR04 RULE 19.4 VIOLATION Improves readability */

/**********************************************
 * Core identifiers
 *********************************************/

#define OS_CORE_NO_DEF                  (1)
#define OS_AUTOSAR_CORE_NO_DEF          (1)
#define OS_NONAUTOSAR_CORE_NO_DEF       (0)

#define OS_CORE_NO                      ((CoreIdType) 1U)
#define OS_AUTOSAR_CORE_NO              ((CoreIdType) 1U)
#define OS_NONAUTOSAR_CORE_NO           ((CoreIdType) 0U)

#define OS_CORE_ID_0                    ((CoreIdType) 0U)

#define OS_CORE_ID_MASTER               OS_CORE_ID_0 /* MR04 RULE 19.4 VIOLATION Improves readability */


/**********************************************
 * Process Configuration
 *********************************************/

#define OS_STACKGUARDINGSIZE            (1U)

/**********************************************
 * Os Hooks Configuration
 *********************************************/

#define OS_ERRORHOOK                    (STD_OFF)      /* [OS_CONF-0036-04] Requirement verified by review */
#define OS_PREAPPHOOK                   (STD_OFF)     /* [OS_CONF-1102-04] Requirement verified by review */
#define OS_POSTAPPHOOK                  (STD_OFF)    /* [OS_CONF-1101-04] Requirement verified by review */
#define OS_PRETASKHOOK                  (STD_OFF)    /* [OS_CONF-0038-04] Requirement verified by review */
#define OS_POSTTASKHOOK                 (STD_OFF)   /* [OS_CONF-0037-04] Requirement verified by review */
#define OS_STARTUPHOOK                  (STD_OFF)    /* [OS_CONF-0040-04] Requirement verified by review */
#define OS_SHUTDOWNHOOK                 (STD_OFF)   /* [OS_CONF-0039-04] Requirement verified by review */
#define OS_PROTECTIONHOOK               (STD_OFF) /* [OS_CONF-0214-04] Requirement verified by review */

#define OS_APP_ERRORHOOK                (STD_OFF)    /* [OS_CONF-0213-05] Requirement verified by review */
#define OS_APP_STARTUPHOOK              (STD_OFF)  /* [OS_CONF-0124-05] Requirement verified by review */
#define OS_APP_SHUTDOWNHOOK             (STD_OFF) /* [OS_CONF-0125-05] Requirement verified by review */
/*================================ EXTERNALS ================================*/

/* ============================== */
#define OS_START_SEC_PRIVATE_CONST
#include OS_MEMMAP_HEADER                    /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

extern CONST(uint8, OS_CONST) Os_SC1_1C_E_SS___IR___590_MPC5607B_MGCGCC;

/* ============================== */
#define OS_STOP_SEC_PRIVATE_CONST
#include OS_MEMMAP_HEADER                    /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

#ifdef _BullseyeCoverage
/* Workaround for Bullseye */
#define OS_START_SEC_PUBLIC_VAR_INIT
#include OS_MEMMAP_HEADER /* KW MISRA.INCL.INSIDE */

extern VAR(uint8, OS_VAR) tempVariableForBullseye;

#define OS_STOP_SEC_PUBLIC_VAR_INIT
#include OS_MEMMAP_HEADER /* KW MISRA.INCL.INSIDE */
#endif /* _BullseyeCoverage */

/**********************************************************************/
#endif /* OS_CFG_H */
/**********************************************************************/
/* End of Os_Cfg.h - Core part */

#ifndef OS_CFG_H_TARGET_
#define OS_CFG_H_TARGET_

/*****************************************************************************/
/****************************** TARGET - START *******************************/
/*****************************************************************************/

#define OS_PLATFORM_REQUIRES_OS_CORE_LOCKINIT

#define OS_USE_Z0
#define OS_Z0_SPRG_NUMBER      2

/*****************************************************************************/
/******************************* TARGET - END* *******************************/
/*****************************************************************************/

#endif /* OS_CFG_H_TARGET_ */

/* End of Os_Cfg.h - Target part */

/*=============================== END OF FILE ===============================*/

