/******************************************************************************
* This file is automatically generated by VSC.
* Do not edit manually.
* VSC Version    : 2.6.8
* Plugin Version : com.mentor.bsw.os.PowerPC.MPC5607B 5.9.0
*==============================================================================
*
* Module:       Os
*
* File Name:    Os_LCfg.c
*
* Description: This file shall contain the configuration Link Time parameters
*
*****************************************************************************/
/*============================== VERSION INFO ===============================*/

#define OS_LCFG_C_SW_MAJOR_VERSION  (5U)
#define OS_LCFG_C_SW_MINOR_VERSION  (9U)
#define OS_LCFG_C_SW_PATCH_VERSION  (0U)

/*=============================== INCLUSIONS ================================*/

#define OS_SOURCE_FILE

#include "Os_LCfg.h"

#include "Os_AlarmCfgTypes.h"
#include "Os_ApplicationCfgTypes.h"
#include "Os_CoreCfgTypes.h"
#include "Os_CounterCfgTypes.h"
#include "Os_ErrorCfgTypes.h"
#include "Os_EventCfgTypes.h"
#include "Os_HookCfgTypes.h"
#include "Os_IocCfgTypes.h"
#include "Os_IsrCfgTypes.h"
#include "Os_MemoryProtectionCfgTypes.h"
#include "Os_ResourceCfgTypes.h"
#include "Os_SchedulerCfgTypes.h"
#include "Os_ScheduleTableCfgTypes.h"
#include "Os_SpinlockCfgTypes.h"
#include "Os_SpinlockLiteCfgTypes.h"
#include "Os_StackSharingCfgTypes.h"
#include "Os_TaskCfgTypes.h"
#include "Os_TimerCfgTypes.h"
#include "Os_TimingProtectionCfgTypes.h"
#include "Os_TrustedFunctionCfgTypes.h"

#include "Os_IocStatic.h"
#include "Os_Context.h"
#include "Os_Core.h"
#include "Os_ApiDispatch.h"

/*============================ MACRO DEFINITIONS ============================*/

/* This macro helps the readability */
#define OS_COUNTOFARRAYELEMENTS(array)           ((uint32)sizeof(array)/(uint32)sizeof((array)[0]))  /* MR04 RULE 19.7 VIOLATION For better performance */

/*===========================================================================*/

/******************************************************************************/
/***************************** KERNEL - START *********************************/
/******************************************************************************/

/* ============================== */
#define OS_START_SEC_CORE_0_VAR_NO_INIT
#include OS_MEMMAP_HEADER                    /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

VAR (Os_StackType, OS_VAR) Os_KernelStack_0 [512U];

/* ============================== */
#define OS_STOP_SEC_CORE_0_VAR_NO_INIT
#include OS_MEMMAP_HEADER                    /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

/* ============================== */
#define OS_START_SEC_PRIVATE_CONST
#include OS_MEMMAP_HEADER                    /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

CONST(uint8,OS_CONST) Os_SC1_1C_E_SS___IR___590_MPC5607B_MGCGCC = (uint8) 0U;

CONST (uint32, OS_VAR) Os_KernelStackSize = 510U;

CONSTP2VAR (Os_StackType, OS_CONST, OS_VAR) Os_KernelStack[OS_CORE_NO] =
{
    &Os_KernelStack_0 [0 + 1U]
};

CONSTP2VAR (Os_StackType, OS_CONST, OS_VAR) Os_KernelStackStart[OS_CORE_NO] =
{
    &Os_KernelStack_0 [512U - 1U - 1U]
};

CONSTP2VAR (Os_StackType, OS_CONST, OS_VAR) Os_KernelStackPtr_0 = &Os_KernelStack_0 [512U - 1U - 1U];


/* ============================== */
#define OS_STOP_SEC_PRIVATE_CONST
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

/******************************************************************************/
/***************************** KERNEL - END ***********************************/
/******************************************************************************/


/******************************************************************************/
/************************** APPLICATION MODE - START **************************/
/******************************************************************************/

/* ============================== */
#define OS_START_SEC_PRIVATE_CONST
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

CONST(AppModeType,OS_CONST) Os_AppModeCount = 1U;

/* ============================== */
#define OS_STOP_SEC_PRIVATE_CONST
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

/******************************************************************************/
/*************************** APPLICATION MODE - END ***************************/
/******************************************************************************/

/******************************************************************************/
/*************************** RESOURCE - START *********************************/
/******************************************************************************/

/* ============================== */
#define OS_START_SEC_PRIVATE_CONST
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

static CONST(Os_AccessStorageType,OS_CONST) Os_RES_SCHEDULER0AccessRights [ 1 ] = { 0x0 };

/* ============================== */
#define OS_STOP_SEC_PRIVATE_CONST
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

/* ============================== */
#define OS_START_SEC_PRIVATE_VAR_NO_INIT
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

VAR(Os_ResourceDynType,OS_VAR) Os_ResourceDyns [1];

/* ============================== */
#define OS_STOP_SEC_PRIVATE_VAR_NO_INIT
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */

#define OS_START_SEC_PRIVATE_CONST
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */
/* ============================== */

/* ============================== */
CONST (Os_ResourceStatType, OS_CONST) Os_ResourceStat [] =
{
    /* RES_SCHEDULER0 */
    {
        /* Os_ResourcePriority     */    1,
        /* Os_ResourceAccessRights */    Os_RES_SCHEDULER0AccessRights ,
        /* Os_ResourceDyn          */    &Os_ResourceDyns[0U]
    },
};

CONST (ResourceType, OS_CONST) Os_ResSchedulerId = 0U;

CONST (Os_ObjectRangeType, OS_CONST) Os_ResourceRange[OS_CORE_NO] =
{
   { ~(Os_ObjectType) 0U, (Os_ObjectType) 0U },   /* Core id: 0 */
};

/* ============================== */
#define OS_STOP_SEC_PRIVATE_CONST
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

/******************************************************************************/
/***************************** RESOURCE - END *********************************/
/******************************************************************************/


/******************************************************************************/
/******************* PROCESS STACK AND CONTEXT - START ************************/
/******************************************************************************/

/******************************* PROCESS STACKS *******************************/

/* ============================== */
#define OS_START_SEC_Os_ComTask_STACK_VAR_NO_INIT
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

static VAR (Os_StackType, OS_VAR)  Os_ComTask_STACK_Array [300U];

/* ============================== */
#define OS_STOP_SEC_Os_ComTask_STACK_VAR_NO_INIT
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

/* ============================== */
#define OS_START_SEC_Os_ModeTask_STACK_VAR_NO_INIT
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

static VAR (Os_StackType, OS_VAR)  Os_ModeTask_STACK_Array [300U];

/* ============================== */
#define OS_STOP_SEC_Os_ModeTask_STACK_VAR_NO_INIT
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

/* ============================== */
#define OS_START_SEC_Os_OsTask_STACK_VAR_NO_INIT
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

static VAR (Os_StackType, OS_VAR)  Os_OsTask_STACK_Array [300U];

/* ============================== */
#define OS_STOP_SEC_Os_OsTask_STACK_VAR_NO_INIT
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

/* ============================== */
#define OS_START_SEC_Os_STARTUP_STACK_VAR_NO_INIT
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

static VAR (Os_StackType, OS_VAR)  Os_STARTUP_STACK_Array [128U];

/* ============================== */
#define OS_STOP_SEC_Os_STARTUP_STACK_VAR_NO_INIT
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */



/****************************** PROCESS CONTEXTS ******************************/

#ifdef OS_CONTEXT_SIZE
  #define OS_CONTEXT_SIZE_0 (OS_CONTEXT_SIZE)
#endif

/* ============================== */
#define OS_START_SEC_Os_STARTUP_CONTEXT_VAR_NO_INIT
#include OS_MEMMAP_HEADER                    /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

static VAR (Os_StackType, OS_VAR)  Os_STARTUP_CONTEXT_Array [OS_CONTEXT_SIZE_0];

/* ============================== */
#define OS_STOP_SEC_Os_STARTUP_CONTEXT_VAR_NO_INIT
#include OS_MEMMAP_HEADER                    /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */
/* ============================== */
#define OS_START_SEC_Os_OsTask_CONTEXT_VAR_NO_INIT
#include OS_MEMMAP_HEADER                    /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

static VAR (Os_StackType, OS_VAR)  Os_OsTask_CONTEXT_Array [OS_CONTEXT_SIZE_0];

/* ============================== */
#define OS_STOP_SEC_Os_OsTask_CONTEXT_VAR_NO_INIT
#include OS_MEMMAP_HEADER                    /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */
/* ============================== */
#define OS_START_SEC_Os_ModeTask_CONTEXT_VAR_NO_INIT
#include OS_MEMMAP_HEADER                    /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

static VAR (Os_StackType, OS_VAR)  Os_ModeTask_CONTEXT_Array [OS_CONTEXT_SIZE_0];

/* ============================== */
#define OS_STOP_SEC_Os_ModeTask_CONTEXT_VAR_NO_INIT
#include OS_MEMMAP_HEADER                    /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */
/* ============================== */
#define OS_START_SEC_Os_ComTask_CONTEXT_VAR_NO_INIT
#include OS_MEMMAP_HEADER                    /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

static VAR (Os_StackType, OS_VAR)  Os_ComTask_CONTEXT_Array [OS_CONTEXT_SIZE_0];

/* ============================== */
#define OS_STOP_SEC_Os_ComTask_CONTEXT_VAR_NO_INIT
#include OS_MEMMAP_HEADER                    /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */


/******************************************************************************/
/*********************** PROCESS STACK AND CONTEXT - END **********************/
/******************************************************************************/


/******************************************************************************/
/******************************* PROCESS - START ******************************/
/******************************************************************************/

/* ============================== */
#define OS_START_SEC_CORE_0_VAR_NO_INIT
#include OS_MEMMAP_HEADER                    /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */


/* ============================== */
#define OS_STOP_SEC_CORE_0_VAR_NO_INIT
#include OS_MEMMAP_HEADER                    /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */


/* ============================== */
#define OS_START_SEC_PRIVATE_CONST
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */


static CONST (Os_AccessStorageType, OS_CONST)  Os_AutoStart_STARTUP [] = { 0x1 };


/* ============================== */
#define OS_STOP_SEC_PRIVATE_CONST
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

/* ============================== */
#define OS_START_SEC_CORE_0_VAR_NO_INIT
#include OS_MEMMAP_HEADER                    /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

STATIC_VAR(Os_SchedulerQueueElementType,OS_VAR) Os_SchedulerQueueElements_0 [ 4 ];

/* ============================== */
#define OS_STOP_SEC_CORE_0_VAR_NO_INIT
#include OS_MEMMAP_HEADER                    /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */


/* ============================== */
#define OS_START_SEC_PRIVATE_VAR_NO_INIT
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

VAR(Os_ProcDynType,OS_VAR) Os_Proc_Dyn[ 4U ];

/* ============================== */
#define OS_STOP_SEC_PRIVATE_VAR_NO_INIT
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

/* ============================== */
#define OS_START_SEC_PRIVATE_CONST
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

static CONST (Os_ProcStackType, OS_CONST)  Os_Proc_Stack[ 4U ] =
{
    /* ComTask */
    {
      /* Os_ProcStackSize */  298U,
      /* Os_ProcStackBase */  &Os_ComTask_STACK_Array [298U]    },

    /* ModeTask */
    {
      /* Os_ProcStackSize */  298U,
      /* Os_ProcStackBase */  &Os_ModeTask_STACK_Array [298U]    },

    /* OsTask */
    {
      /* Os_ProcStackSize */  298U,
      /* Os_ProcStackBase */  &Os_OsTask_STACK_Array [298U]    },

    /* STARTUP */
    {
      /* Os_ProcStackSize */  126U,
      /* Os_ProcStackBase */  &Os_STARTUP_STACK_Array [126U]    }

};

CONST (Os_ProcStatType, OS_CONST) Os_Proc_Stat[] =
{
    /* ComTask */
    {
      /* Os_ProcId                     */  0U,
      /* Os_ProcDyn                    */  &Os_Proc_Dyn [0U],
      /* Os_ProcStack                  */  &Os_Proc_Stack [0U],
      /* Os_ProcKind                   */  Os_Proc_Task,
      /* Os_ProcEventRights            */  0x1ULL,
      /* Os_ProcPriority               */  1U,
      /* Os_ProcRunPriority            */  1U,
      /* Os_ProcMaxActivations         */  1U,
      /* Os_ProcContext                */  &Os_ComTask_CONTEXT_Array [0U],
      /* Os_ProcEntryPoint             */  &OS_TASK_ComTask,
      /* Os_ProcAutoStart              */  NULL_PTR,
      /* Os_ProcResourceCount          */  0U,
      /* Os_ProcResourceStack          */  NULL_PTR,
      /* Os_ProcQueueElements          */  &Os_SchedulerQueueElements_0 [0U],
      /* Os_ProcIsrPlatformConfig      */  NULL_PTR
    },
    /* ModeTask */
    {
      /* Os_ProcId                     */  1U,
      /* Os_ProcDyn                    */  &Os_Proc_Dyn [1U],
      /* Os_ProcStack                  */  &Os_Proc_Stack [1U],
      /* Os_ProcKind                   */  Os_Proc_Task,
      /* Os_ProcEventRights            */  0x2ULL,
      /* Os_ProcPriority               */  1U,
      /* Os_ProcRunPriority            */  1U,
      /* Os_ProcMaxActivations         */  1U,
      /* Os_ProcContext                */  &Os_ModeTask_CONTEXT_Array [0U],
      /* Os_ProcEntryPoint             */  &OS_TASK_ModeTask,
      /* Os_ProcAutoStart              */  NULL_PTR,
      /* Os_ProcResourceCount          */  0U,
      /* Os_ProcResourceStack          */  NULL_PTR,
      /* Os_ProcQueueElements          */  &Os_SchedulerQueueElements_0 [1U],
      /* Os_ProcIsrPlatformConfig      */  NULL_PTR
    },
    /* OsTask */
    {
      /* Os_ProcId                     */  2U,
      /* Os_ProcDyn                    */  &Os_Proc_Dyn [2U],
      /* Os_ProcStack                  */  &Os_Proc_Stack [2U],
      /* Os_ProcKind                   */  Os_Proc_Task,
      /* Os_ProcEventRights            */  0x0ULL,
      /* Os_ProcPriority               */  1U,
      /* Os_ProcRunPriority            */  1U,
      /* Os_ProcMaxActivations         */  1U,
      /* Os_ProcContext                */  &Os_OsTask_CONTEXT_Array [0U],
      /* Os_ProcEntryPoint             */  &OS_TASK_OsTask,
      /* Os_ProcAutoStart              */  NULL_PTR,
      /* Os_ProcResourceCount          */  0U,
      /* Os_ProcResourceStack          */  NULL_PTR,
      /* Os_ProcQueueElements          */  &Os_SchedulerQueueElements_0 [2U],
      /* Os_ProcIsrPlatformConfig      */  NULL_PTR
    },
    /* STARTUP */
    {
      /* Os_ProcId                     */  3U,
      /* Os_ProcDyn                    */  &Os_Proc_Dyn [3U],
      /* Os_ProcStack                  */  &Os_Proc_Stack [3U],
      /* Os_ProcKind                   */  Os_Proc_Task,
      /* Os_ProcEventRights            */  0x0ULL,
      /* Os_ProcPriority               */  1U,
      /* Os_ProcRunPriority            */  1U,
      /* Os_ProcMaxActivations         */  1U,
      /* Os_ProcContext                */  &Os_STARTUP_CONTEXT_Array [0U],
      /* Os_ProcEntryPoint             */  &OS_TASK_STARTUP,
      /* Os_ProcAutoStart              */  &Os_AutoStart_STARTUP [0U],
      /* Os_ProcResourceCount          */  0U,
      /* Os_ProcResourceStack          */  NULL_PTR,
      /* Os_ProcQueueElements          */  &Os_SchedulerQueueElements_0 [3U],
      /* Os_ProcIsrPlatformConfig      */  NULL_PTR
    }
};

/* ============================== */
#define OS_STOP_SEC_PRIVATE_CONST
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

/* ============================== */
#define OS_START_SEC_CORE_0_VAR_NO_INIT
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

STATIC_VAR (Os_SchedulerQueueType, OS_VAR) Os_SchedulerQueuesOn_0 [ 3 ];

static P2CONST (Os_ProcStatType, OS_VAR, OS_CONST) Os_IsrCurrent_0 [ 1 ];

/* ============================== */
#define OS_STOP_SEC_CORE_0_VAR_NO_INIT
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

/* ============================== */
#define OS_START_SEC_PRIVATE_CONST
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

CONST (Os_SchedulerQueueStructureType, OS_CONST) Os_SchedulerQueueStruct[ OS_CORE_NO ] = {
    {
        /* Os_ProcMaxTaskPrio     */    (1U),
        /* Os_ProcMaxCAT2Prio     */    (2U),
        /* Os_ProcMaxCAT1Prio     */    (2U),
        /* Os_IsrCAT0Prio         */    (1U),
        /* Os_IsrCAT1Prio         */    (1U),
        /* Os_IsrCAT2Prio         */    (1U),
        /* Os_SchedulerQueueCount */    OS_COUNTOFARRAYELEMENTS(Os_SchedulerQueuesOn_0),
        /* Os_SchedulerQueues     */    &Os_SchedulerQueuesOn_0 [0]
    }
};

CONST (ProcType, OS_CONST) Os_IsrCurrentDeepness[OS_CORE_NO]={
    1U
};

CONSTP2VAR (P2CONST (Os_ProcStatType, OS_VAR, OS_CONST), OS_VAR, OS_CONST) Os_IsrCurrentIsr[OS_CORE_NO]={
    &Os_IsrCurrent_0 [0]
};


CONST (Os_ObjectRangeType, OS_CONST) Os_ProcRange[OS_CORE_NO] =
{
    { 0U, 3U }   /* Core id: 0 */
};

/******************************************************************************/
/***************************** PROCESS - END **********************************/
/******************************************************************************/


/******************************************************************************/
/***************************** ALARM - START **********************************/
/******************************************************************************/

/* ============================== */
#define OS_STOP_SEC_PRIVATE_CONST
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

/* ============================== */
#define OS_START_SEC_PRIVATE_VAR_NO_INIT
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

VAR(Os_AlarmDynType, OS_VAR) Os_AlarmDyns [1U];

/* ============================== */
#define OS_STOP_SEC_PRIVATE_VAR_NO_INIT
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

/* ============================== */
#define OS_START_SEC_PRIVATE_CONST
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

static CONST(Os_AlarmActionType, OS_CONST) Os_AlarmActions[] = {
    {
        Os_AlarmAction_ActivateTask,
        {
            /* Os_AlarmActionSetEvent             */    { 0, 0 },
            /* Os_AlarmActionActivateTaskType     */    { OsTask },
            /* Os_AlarmActionIncrementCounterType */    { 0 },
        }
    }
};

static CONST(Os_AlarmStatType,OS_CONST) Os_AlarmStatArray [] =
{
    /* Rte_Al_OsTask */
    {
        /* Dynamic           */     &Os_AlarmDyns[ 0U ],
        /* Counter           */     &Os_CounterStat[ 0U ],  /* OsCounter */
        /* AlarmAction       */     &Os_AlarmActions[ 0U ],
        /* Os_AlarmAutoStart */     NULL_PTR
    }
};

CONSTP2CONST(Os_AlarmStatType,OS_CONST,OS_CONST) Os_AlarmStat = &Os_AlarmStatArray[0];

CONST (Os_ObjectRangeType, OS_CONST) Os_AlarmRange[OS_CORE_NO] =
{
    { 0U, 0U }   /* Core id: 0 */
};

/******************************************************************************/
/****************************** ALARM - END ***********************************/
/******************************************************************************/


/******************************************************************************/
/**************************** COUNTER - START *********************************/
/******************************************************************************/


/* ============================== */
#define OS_STOP_SEC_PRIVATE_CONST
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

/* ============================== */
#define  OS_START_SEC_PRIVATE_VAR_NO_INIT
#include OS_MEMMAP_HEADER                    /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

STATIC_VAR (Os_CounterEPType, OS_VAR)  Os_CounterEPsOfOsCounter [ 2U ] ;
STATIC_VAR (Os_CounterEPActionType, OS_VAR)  Os_CounterActionsOfOsCounter [ 2U ];


/* ============================== */
#define OS_STOP_SEC_PRIVATE_VAR_NO_INIT
#include OS_MEMMAP_HEADER                    /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

/* ============================== */
#define  OS_START_SEC_PRIVATE_VAR_NO_INIT
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

VAR (Os_CounterDynType, OS_VAR) Os_CounterDyn[1U];

/* ============================== */
#define OS_STOP_SEC_PRIVATE_VAR_NO_INIT
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

/* ============================== */
#define OS_START_SEC_PRIVATE_CONST
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

CONST (Os_ObjectRangeType, OS_CONST) Os_CounterEPRange[OS_CORE_NO] =
{
    { 0U, 0U },   /* Core id: 0 */
};


CONST (Os_CounterStatType, OS_CONST) Os_CounterStat [] =
{
    {                               /* OsCounter */
      /* Os_CounterKind         */  OS_HARDWARE,
      /* Os_CounterMaxValue     */  OSMAXALLOWEDVALUE_OsCounter,
      /* Os_CounterMinCycle     */  OSMINCYCLE_OsCounter,
      /* Os_CounterTicksPerBase */  OSTICKSPERBASE_OsCounter,
      /* Os_CounterPoolSize     */  2U,
      /* Os_CounterRegistry     */  &Os_CounterDyn [OsCounter],
      /* Os_CounterEPs          */  &Os_CounterEPsOfOsCounter [0U],
      /* Os_CounterActions      */  &Os_CounterActionsOfOsCounter [0U],
      /* Os_TimerId             */  0U
    }
};

CONST (Os_ObjectRangeType, OS_CONST) Os_CounterRange[OS_CORE_NO] =
{
    { 0U, 0U }   /* Core id: 0 */
};

/******************************************************************************/
/****************************** COUNTER - END *********************************/
/******************************************************************************/


/******************************************************************************/
/************************* SCHEDULETABLE - START ******************************/
/******************************************************************************/

 
CONSTP2CONST(Os_SchTblStatType,OS_CONST,OS_CONST) Os_SchTblStat = NULL_PTR;


CONST (Os_ObjectRangeType, OS_CONST) Os_SchTblRange[OS_CORE_NO] =
{
    { ~(Os_ObjectType) 0U, (Os_ObjectType) 0U }   /* Core id: 0 */
};

/* ============================== */
#define OS_STOP_SEC_PRIVATE_CONST
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

/******************************************************************************/
/************************** SCHEDULETABLE - END *******************************/
/******************************************************************************/





/**********************************************************************/
/********************** CORES - BEGIN *********************************/
/**********************************************************************/

/* ============================== */
#define OS_START_SEC_PRIVATE_VAR_NO_INIT
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

#if defined(OS_MODULE_MULTICORE)
  VAR(Os_DispatcherType, OS_VAR) Os_Dispatcher[OS_CORE_NO];
#endif

/* ============================== */
#define OS_STOP_SEC_PRIVATE_VAR_NO_INIT
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

/* ============================== */
#define OS_START_SEC_PRIVATE_VAR_INIT
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

VAR(Os_Core_DynInitSharedType, OS_VAR) Os_Core_DynInitShared[OS_CORE_NO] =
{
    /* Physical core 0 */
    {
        /* Os_StartOsFunc     */ &Os_StartOsFirstTime,
        /* Os_CoreStateType   */ OS_CORE_ACTIVATED,
        /* Os_CoreStartedType */ OS_CORE_START_INIT,
        /* AppModeType        */ (AppModeType)OS_APPMODEID_INVALID,
        /* IdleModeType       */ IDLE_NO_HALT
    }
};

/* ============================== */
#define OS_STOP_SEC_PRIVATE_VAR_INIT
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

#define OS_START_SEC_CORE_0_VAR_INIT
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

VAR (Os_Core_DynInitType, OS_VAR) Os_Core_DynInit_0 =
{
    /* Os_IsrDynInit */
    {
      /* Os_CurrentUserModePriority  */  0U,
      /* Os_UserModePriorityChanged  */  FALSE,
      /* Os_DisableAllCount          */  (uint32) 0U,
      /* Os_SuspendAllCount          */  (uint32) 0U,
      /* Os_SuspendOSCount           */  (uint32) 0U,
      /* Os_SavedIsrLevel            */  (uint32) 0U,
      /* Os_SavedOSIsrLevel          */  (uint32) 0U,
      /* Os_GlobalSuspendCount       */  (uint32) 0U
    },
    /* Os_SchedulerDynInit */
    {
        /* Os_SchedulerCurrentProc   */  NULL_PTR,
    },
};

/* ============================== */
#define OS_STOP_SEC_CORE_0_VAR_INIT
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

/* ============================== */
#define OS_START_SEC_CORE_0_VAR_NO_INIT
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

VAR (Os_Core_DynType, OS_VAR) Os_Core_Dyn_0;

/* ============================== */
#define OS_STOP_SEC_CORE_0_VAR_NO_INIT
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

#ifdef OS_MODULE_PUBLICDATA_VARINIT

/* ============================== */
  #define OS_START_SEC_PUBLIC_VAR_INIT
  #include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

VAR (Os_PublicData_VarInitType, OS_VAR) Os_PublicDataVarInit_0 =
{
    /* Os_ISRServices */ &Os_ISRServicesDefault,
};

/* ============================== */
  #define OS_STOP_SEC_PUBLIC_VAR_INIT
  #include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

#endif /* OS_MODULE_PUBLICDATA_VARINIT */

#ifdef OS_MODULE_PUBLICDATA_NOINIT

/* ============================== */
  #define OS_START_SEC_PUBLIC_VAR_NO_INIT
  #include OS_MEMMAP_HEADER                    /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

VAR (Os_PublicData_NoInitType, OS_VAR) Os_PublicDataVarNoInit_0;

/* ============================== */
  #define OS_STOP_SEC_PUBLIC_VAR_NO_INIT
  #include OS_MEMMAP_HEADER                    /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

#endif /* OS_MODULE_PUBLICDATA_NOINIT */


#ifdef OS_MODULE_PUBLICDATA

/* ============================== */
  #define OS_START_SEC_PUBLIC_CONST
  #include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

CONST (Os_PublicDataType, OS_CONST) Os_PublicData[OS_CORE_NO] =
{
    {
      #ifdef OS_MODULE_PUBLICDATA_NOINIT
        /* Os_PublicDataNoInitRef  */  &Os_PublicDataVarNoInit_0,
      #endif
      #ifdef OS_MODULE_PUBLICDATA_VARINIT
        /* Os_PublicDataVarInitRef */  &Os_PublicDataVarInit_0,
      #endif
    }
};

/* ============================== */
  #define OS_STOP_SEC_PUBLIC_CONST
  #include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

#endif /* OS_MODULE_PUBLICDATA */

/* ============================== */
#define OS_START_SEC_PRIVATE_CONST
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

CONST (Os_Core_StatType, OS_CONST) Os_Core_Stat[OS_CORE_NO] =
{
    /* Physical core 0 */
    {
        /* Os_Core_DynInit                */    &Os_Core_DynInit_0,
        /* Os_Core_Dyn                    */    &Os_Core_Dyn_0,
        /* Os_PrepareContextFunctionType  */    &Os_PrepareContext_Z0,
        /* Os_GetStackPointerFunctionType */    &Os_GetStackPointer_Z0
    }
};

/* ============================== */
#define OS_STOP_SEC_PRIVATE_CONST
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

/**********************************************************************/
/*********************** CORES - END **********************************/
/**********************************************************************/

/**********************************************************************/
/********************** TIMERS - BEGIN ********************************/
/**********************************************************************/
/* ============================== */
#define  OS_START_SEC_PRIVATE_VAR_NO_INIT
#include OS_MEMMAP_HEADER                    /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */
STATIC_VAR(Os_TimerCounterDynType, OS_VAR) Os_OsTimer;

/* ============================== */
#define  OS_STOP_SEC_PRIVATE_VAR_NO_INIT
#include OS_MEMMAP_HEADER                    /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

/* ============================== */
#define OS_START_SEC_PRIVATE_CONST
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

static CONST (Os_TimerType, OS_CONST) Os_TimersListOnCore0 [1] = {
    0U, /* OsTimer */
};

static CONSTP2CONST (Os_CounterStatType, OS_CONST, OS_CONST) Os_CountersOfOsTimer [1U] =
{
    &Os_CounterStat[0U],   /* OsCounter */
};

CONST (Os_TimersListOnCoreType, OS_CONST) Os_TimersListOnCores[OS_CORE_NO] = {
    /* Core 0 */
    {
        /* Os_TimersList     */ &Os_TimersListOnCore0 [0U],
        /* Os_NumberOfTimers */ 1U
    }
};

CONST (Os_TimerConfType, OS_CONST) Os_TimerConf[1] = {
    /* OsTimer */
    {
        /* Os_NumberOfCounters        */ 1U,
        /* Os_Counters                */ &Os_CountersOfOsTimer [0U], /* KW STRONG.TYPE.ASSIGN.INIT */
        /* Os_TimerDyn                */ &Os_OsTimer,
        /* Os_IsrPltConfig            */ &Os_IsrPlatformConfig [0U],
        /* Os_TimerPlatformConfigType */ &Os_TimerPlatformConf [0U],
        /* Os_TimerMultiplicator      */ 0x61A80U /* 400000 */,
        /* Os_TimerMaxTickCount       */ 0x29F1U
    }
};


/**********************************************************************/
/************************ TIMERS - END ********************************/
/**********************************************************************/


/**********************************************************************/
/************************* ISR - START ********************************/
/**********************************************************************/

CONSTP2CONST (Os_IsrPlatformConfigType, OS_CONST, OS_CONST)  Os_IsrCAT1PlatformConfig [] =
{
    NULL_PTR
};

CONST (Os_ObjectRangeType, OS_CONST) Os_IsrCAT1PlatformConfigRange[OS_CORE_NO] =
{
    { ~(Os_ObjectType)0U, (Os_ObjectType)0U } /* Core id: 0 */
};


/* ============================== */
#define OS_STOP_SEC_PRIVATE_CONST
#include OS_MEMMAP_HEADER /* MR04 RULE 19.1 VIOLATION Autosar requirement to be implemented this way */
/* ============================== */

/**********************************************************************/
/************************** ISR - END *********************************/
/**********************************************************************/

#define OS_START_SEC_PRIVATE_CONST
#include OS_MEMMAP_HEADER

CONST (Os_IsrPlatformConfigType, OS_CONST) Os_IsrPlatformConfig[1] =
{
    { 0x3BU, (Os_IsrPlatformLevelType)(((uint16)1U) | OS_INTC_PSR_PRC_SEL(1U)) },
};

CONST (uint32, OS_CONST) Os_IsrPlatformConfigSize = 1U;


CONST (uint32, OS_CONST) Os_IsrIvpr[OS_CORE_NO] =
{
    0x40000000U,
};

CONST (Os_TimerPlatformConfigType, OS_CONST) Os_TimerPlatformConf[] =
{
    {
    /* Os_TimerChannelId   */ 0
    },
};

CONST (uint8, OS_CONST) Os_TimerFreezeInDebug = 1U;


#define OS_STOP_SEC_PRIVATE_CONST
#include OS_MEMMAP_HEADER

#define OS_START_SEC_PRIVATE_CODE
#include OS_MEMMAP_HEADER


#define OS_STOP_SEC_PRIVATE_CODE
#include OS_MEMMAP_HEADER

#define OS_START_SEC_PRIVATE_CONST
#include OS_MEMMAP_HEADER



#define OS_STOP_SEC_PRIVATE_CONST
#include OS_MEMMAP_HEADER

/**********************************************************************/



/* End Os_LCfg.c */
