/******************************************************************************
 *
 *                          Copyright 2020 Siemens
 *                           All Rights Reserved
 *
 * THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY INFORMATION WHICH IS
 * THE PROPERTY OF SIEMENS OR ITS LICENSORS AND IS SUBJECT TO LICENSE TERMS.
 *
 ******************************************************************************
 *
 * Module:      MemMap
 *
 * File Name:   Os_MemMap.h
 *
 * Description: Memory mapping header file.
 *
 *              NOTE! This file is automatically generated!
 *              Do NOT edit manually!
 *
 ******************************************************************************/


/*=============================== INCLUSIONS =================================*/

/*============================ TYPE DEFINITIONS ==============================*/

/*============================== VERSION INFO ================================*/

/** General Information *******************************************************/

#ifdef MEMMAP_VENDOR_ID
  #if (MEMMAP_VENDOR_ID != 31U)
    #error "Redefinition of MEMMAP_VENDOR_ID macro with different value!"
  #endif
#else
  #define MEMMAP_VENDOR_ID                     (31U)
#endif

#ifdef MEMMAP_MODULE_ID
  #if (MEMMAP_MODULE_ID != 195U)
    #error "Redefinition of MEMMAP_MODULE_ID macro with different value!"
  #endif
#else
  #define MEMMAP_MODULE_ID                     (195U)
#endif


/** AUTOSAR Version Information ***********************************************/

#ifdef MEMMAP_AR_RELEASE_MAJOR_VERSION
  #if (MEMMAP_AR_RELEASE_MAJOR_VERSION != 4U)
    #error "Redefinition of MEMMAP_AR_RELEASE_MAJOR_VERSION macro with different value!"
  #endif
#else
  #define MEMMAP_AR_RELEASE_MAJOR_VERSION      (4U)
#endif

#ifdef MEMMAP_AR_RELEASE_MINOR_VERSION
  #if (MEMMAP_AR_RELEASE_MINOR_VERSION != 2U)
    #error "Redefinition of MEMMAP_AR_RELEASE_MINOR_VERSION macro with different value!"
  #endif
#else
  #define MEMMAP_AR_RELEASE_MINOR_VERSION      (2U)
#endif

#ifdef MEMMAP_AR_RELEASE_REVISION_VERSION
  #if (MEMMAP_AR_RELEASE_REVISION_VERSION != 2U)
    #error "Redefinition of MEMMAP_AR_RELEASE_REVISION_VERSION macro with different value!"
  #endif
#else
  #define MEMMAP_AR_RELEASE_REVISION_VERSION   (2U)
#endif


/** Software Version Information **********************************************/

#ifdef MEMMAP_SW_MAJOR_VERSION
  #if (MEMMAP_SW_MAJOR_VERSION != 3U)
    #error "Redefinition of MEMMAP_SW_MAJOR_VERSION macro with different value!"
  #endif
#else
  #define MEMMAP_SW_MAJOR_VERSION              (3U)
#endif

#ifdef MEMMAP_SW_MINOR_VERSION
  #if (MEMMAP_SW_MINOR_VERSION != 10U)
    #error "Redefinition of MEMMAP_SW_MINOR_VERSION macro with different value!"
  #endif
#else
  #define MEMMAP_SW_MINOR_VERSION              (10U)
#endif

#ifdef MEMMAP_SW_PATCH_VERSION
  #if (MEMMAP_SW_PATCH_VERSION != 2U)
    #error "Redefinition of MEMMAP_SW_PATCH_VERSION macro with different value!"
  #endif
#else
  #define MEMMAP_SW_PATCH_VERSION              (2U)
#endif


/*============================ MACRO DEFINITIONS =============================*/

#define MEMMAP_SECTION_NOT_FOUND

#if 0

/******************************************************************************/
/** OS BSW                                                                   **/
/******************************************************************************/

/** OS - PRIVATE_CODE *********************************************************/
#elif defined OS_STOP_SEC_PRIVATE_CODE
    #if defined OS_START_SEC_PRIVATE_CODE
        #undef OS_START_SEC_PRIVATE_CODE /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef OS_STOP_SEC_PRIVATE_CODE /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "OS_STOP_SEC_PRIVATE_CODE: This section has not been previously started!"
    #endif
#elif defined OS_START_SEC_PRIVATE_CODE
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "OS_START_SEC_PRIVATE_CODE: Another section which is previously started has not been stopped!"
    #endif

/** OS - PRIVATE_CONST ********************************************************/
#elif defined OS_STOP_SEC_PRIVATE_CONST
    #if defined OS_START_SEC_PRIVATE_CONST
        #undef OS_START_SEC_PRIVATE_CONST /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef OS_STOP_SEC_PRIVATE_CONST /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "OS_STOP_SEC_PRIVATE_CONST: This section has not been previously started!"
    #endif
#elif defined OS_START_SEC_PRIVATE_CONST
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "OS_START_SEC_PRIVATE_CONST: Another section which is previously started has not been stopped!"
    #endif

/** OS - PRIVATE_VAR_INIT *****************************************************/
#elif defined OS_STOP_SEC_PRIVATE_VAR_INIT
    #if defined OS_START_SEC_PRIVATE_VAR_INIT
        #undef OS_START_SEC_PRIVATE_VAR_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef OS_STOP_SEC_PRIVATE_VAR_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "OS_STOP_SEC_PRIVATE_VAR_INIT: This section has not been previously started!"
    #endif
#elif defined OS_START_SEC_PRIVATE_VAR_INIT
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "OS_START_SEC_PRIVATE_VAR_INIT: Another section which is previously started has not been stopped!"
    #endif

/** OS - CORE_0_VAR_INIT ******************************************************/
#elif defined OS_STOP_SEC_CORE_0_VAR_INIT
    #if defined OS_START_SEC_CORE_0_VAR_INIT
        #undef OS_START_SEC_CORE_0_VAR_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef OS_STOP_SEC_CORE_0_VAR_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "OS_STOP_SEC_CORE_0_VAR_INIT: This section has not been previously started!"
    #endif
#elif defined OS_START_SEC_CORE_0_VAR_INIT
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "OS_START_SEC_CORE_0_VAR_INIT: Another section which is previously started has not been stopped!"
    #endif

/** OS - PRIVATE_VAR_NO_INIT **************************************************/
#elif defined OS_STOP_SEC_PRIVATE_VAR_NO_INIT
    #if defined OS_START_SEC_PRIVATE_VAR_NO_INIT
        #undef OS_START_SEC_PRIVATE_VAR_NO_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef OS_STOP_SEC_PRIVATE_VAR_NO_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "OS_STOP_SEC_PRIVATE_VAR_NO_INIT: This section has not been previously started!"
    #endif
#elif defined OS_START_SEC_PRIVATE_VAR_NO_INIT
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "OS_START_SEC_PRIVATE_VAR_NO_INIT: Another section which is previously started has not been stopped!"
    #endif

/** OS - CORE_0_VAR_NO_INIT ***************************************************/
#elif defined OS_STOP_SEC_CORE_0_VAR_NO_INIT
    #if defined OS_START_SEC_CORE_0_VAR_NO_INIT
        #undef OS_START_SEC_CORE_0_VAR_NO_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef OS_STOP_SEC_CORE_0_VAR_NO_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "OS_STOP_SEC_CORE_0_VAR_NO_INIT: This section has not been previously started!"
    #endif
#elif defined OS_START_SEC_CORE_0_VAR_NO_INIT
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "OS_START_SEC_CORE_0_VAR_NO_INIT: Another section which is previously started has not been stopped!"
    #endif

/** OS - PUBLIC_CODE **********************************************************/
#elif defined OS_STOP_SEC_PUBLIC_CODE
    #if defined OS_START_SEC_PUBLIC_CODE
        #undef OS_START_SEC_PUBLIC_CODE /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef OS_STOP_SEC_PUBLIC_CODE /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "OS_STOP_SEC_PUBLIC_CODE: This section has not been previously started!"
    #endif
#elif defined OS_START_SEC_PUBLIC_CODE
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "OS_START_SEC_PUBLIC_CODE: Another section which is previously started has not been stopped!"
    #endif

/** OS - PUBLIC_CONST *********************************************************/
#elif defined OS_STOP_SEC_PUBLIC_CONST
    #if defined OS_START_SEC_PUBLIC_CONST
        #undef OS_START_SEC_PUBLIC_CONST /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef OS_STOP_SEC_PUBLIC_CONST /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "OS_STOP_SEC_PUBLIC_CONST: This section has not been previously started!"
    #endif
#elif defined OS_START_SEC_PUBLIC_CONST
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "OS_START_SEC_PUBLIC_CONST: Another section which is previously started has not been stopped!"
    #endif

/** OS - PUBLIC_VAR_INIT ******************************************************/
#elif defined OS_STOP_SEC_PUBLIC_VAR_INIT
    #if defined OS_START_SEC_PUBLIC_VAR_INIT
        #undef OS_START_SEC_PUBLIC_VAR_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef OS_STOP_SEC_PUBLIC_VAR_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "OS_STOP_SEC_PUBLIC_VAR_INIT: This section has not been previously started!"
    #endif
#elif defined OS_START_SEC_PUBLIC_VAR_INIT
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "OS_START_SEC_PUBLIC_VAR_INIT: Another section which is previously started has not been stopped!"
    #endif

/** OS - PUBLIC_VAR_NO_INIT ***************************************************/
#elif defined OS_STOP_SEC_PUBLIC_VAR_NO_INIT
    #if defined OS_START_SEC_PUBLIC_VAR_NO_INIT
        #undef OS_START_SEC_PUBLIC_VAR_NO_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef OS_STOP_SEC_PUBLIC_VAR_NO_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "OS_STOP_SEC_PUBLIC_VAR_NO_INIT: This section has not been previously started!"
    #endif
#elif defined OS_START_SEC_PUBLIC_VAR_NO_INIT
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "OS_START_SEC_PUBLIC_VAR_NO_INIT: Another section which is previously started has not been stopped!"
    #endif

/** OS - STARTUP_CODE *********************************************************/
#elif defined OS_STOP_SEC_STARTUP_CODE
    #if defined OS_START_SEC_STARTUP_CODE
        #undef OS_START_SEC_STARTUP_CODE /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef OS_STOP_SEC_STARTUP_CODE /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "OS_STOP_SEC_STARTUP_CODE: This section has not been previously started!"
    #endif
#elif defined OS_START_SEC_STARTUP_CODE
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "OS_START_SEC_STARTUP_CODE: Another section which is previously started has not been stopped!"
    #endif

/** OS - STARTUP_CONST ********************************************************/
#elif defined OS_STOP_SEC_STARTUP_CONST
    #if defined OS_START_SEC_STARTUP_CONST
        #undef OS_START_SEC_STARTUP_CONST /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef OS_STOP_SEC_STARTUP_CONST /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "OS_STOP_SEC_STARTUP_CONST: This section has not been previously started!"
    #endif
#elif defined OS_START_SEC_STARTUP_CONST
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "OS_START_SEC_STARTUP_CONST: Another section which is previously started has not been stopped!"
    #endif

/** OS - STARTUP_VAR_INIT *****************************************************/
#elif defined OS_STOP_SEC_STARTUP_VAR_INIT
    #if defined OS_START_SEC_STARTUP_VAR_INIT
        #undef OS_START_SEC_STARTUP_VAR_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef OS_STOP_SEC_STARTUP_VAR_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "OS_STOP_SEC_STARTUP_VAR_INIT: This section has not been previously started!"
    #endif
#elif defined OS_START_SEC_STARTUP_VAR_INIT
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "OS_START_SEC_STARTUP_VAR_INIT: Another section which is previously started has not been stopped!"
    #endif

/** OS - STARTUP_VAR_NO_INIT **************************************************/
#elif defined OS_STOP_SEC_STARTUP_VAR_NO_INIT
    #if defined OS_START_SEC_STARTUP_VAR_NO_INIT
        #undef OS_START_SEC_STARTUP_VAR_NO_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef OS_STOP_SEC_STARTUP_VAR_NO_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "OS_STOP_SEC_STARTUP_VAR_NO_INIT: This section has not been previously started!"
    #endif
#elif defined OS_START_SEC_STARTUP_VAR_NO_INIT
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "OS_START_SEC_STARTUP_VAR_NO_INIT: Another section which is previously started has not been stopped!"
    #endif

/** OS - ComTask_CODE *********************************************************/
#elif defined OS_STOP_SEC_ComTask_CODE
    #if defined OS_START_SEC_ComTask_CODE
        #undef OS_START_SEC_ComTask_CODE /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef OS_STOP_SEC_ComTask_CODE /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "OS_STOP_SEC_ComTask_CODE: This section has not been previously started!"
    #endif
#elif defined OS_START_SEC_ComTask_CODE
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "OS_START_SEC_ComTask_CODE: Another section which is previously started has not been stopped!"
    #endif

/** OS - ComTask_CONST ********************************************************/
#elif defined OS_STOP_SEC_ComTask_CONST
    #if defined OS_START_SEC_ComTask_CONST
        #undef OS_START_SEC_ComTask_CONST /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef OS_STOP_SEC_ComTask_CONST /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "OS_STOP_SEC_ComTask_CONST: This section has not been previously started!"
    #endif
#elif defined OS_START_SEC_ComTask_CONST
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "OS_START_SEC_ComTask_CONST: Another section which is previously started has not been stopped!"
    #endif

/** OS - ComTask_VAR_INIT *****************************************************/
#elif defined OS_STOP_SEC_ComTask_VAR_INIT
    #if defined OS_START_SEC_ComTask_VAR_INIT
        #undef OS_START_SEC_ComTask_VAR_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef OS_STOP_SEC_ComTask_VAR_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "OS_STOP_SEC_ComTask_VAR_INIT: This section has not been previously started!"
    #endif
#elif defined OS_START_SEC_ComTask_VAR_INIT
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "OS_START_SEC_ComTask_VAR_INIT: Another section which is previously started has not been stopped!"
    #endif

/** OS - ComTask_VAR_NO_INIT **************************************************/
#elif defined OS_STOP_SEC_ComTask_VAR_NO_INIT
    #if defined OS_START_SEC_ComTask_VAR_NO_INIT
        #undef OS_START_SEC_ComTask_VAR_NO_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef OS_STOP_SEC_ComTask_VAR_NO_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "OS_STOP_SEC_ComTask_VAR_NO_INIT: This section has not been previously started!"
    #endif
#elif defined OS_START_SEC_ComTask_VAR_NO_INIT
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "OS_START_SEC_ComTask_VAR_NO_INIT: Another section which is previously started has not been stopped!"
    #endif

/** OS - ModeTask_CODE ********************************************************/
#elif defined OS_STOP_SEC_ModeTask_CODE
    #if defined OS_START_SEC_ModeTask_CODE
        #undef OS_START_SEC_ModeTask_CODE /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef OS_STOP_SEC_ModeTask_CODE /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "OS_STOP_SEC_ModeTask_CODE: This section has not been previously started!"
    #endif
#elif defined OS_START_SEC_ModeTask_CODE
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "OS_START_SEC_ModeTask_CODE: Another section which is previously started has not been stopped!"
    #endif

/** OS - ModeTask_CONST *******************************************************/
#elif defined OS_STOP_SEC_ModeTask_CONST
    #if defined OS_START_SEC_ModeTask_CONST
        #undef OS_START_SEC_ModeTask_CONST /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef OS_STOP_SEC_ModeTask_CONST /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "OS_STOP_SEC_ModeTask_CONST: This section has not been previously started!"
    #endif
#elif defined OS_START_SEC_ModeTask_CONST
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "OS_START_SEC_ModeTask_CONST: Another section which is previously started has not been stopped!"
    #endif

/** OS - ModeTask_VAR_INIT ****************************************************/
#elif defined OS_STOP_SEC_ModeTask_VAR_INIT
    #if defined OS_START_SEC_ModeTask_VAR_INIT
        #undef OS_START_SEC_ModeTask_VAR_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef OS_STOP_SEC_ModeTask_VAR_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "OS_STOP_SEC_ModeTask_VAR_INIT: This section has not been previously started!"
    #endif
#elif defined OS_START_SEC_ModeTask_VAR_INIT
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "OS_START_SEC_ModeTask_VAR_INIT: Another section which is previously started has not been stopped!"
    #endif

/** OS - ModeTask_VAR_NO_INIT *************************************************/
#elif defined OS_STOP_SEC_ModeTask_VAR_NO_INIT
    #if defined OS_START_SEC_ModeTask_VAR_NO_INIT
        #undef OS_START_SEC_ModeTask_VAR_NO_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef OS_STOP_SEC_ModeTask_VAR_NO_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "OS_STOP_SEC_ModeTask_VAR_NO_INIT: This section has not been previously started!"
    #endif
#elif defined OS_START_SEC_ModeTask_VAR_NO_INIT
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "OS_START_SEC_ModeTask_VAR_NO_INIT: Another section which is previously started has not been stopped!"
    #endif

/** OS - OsTask_CODE **********************************************************/
#elif defined OS_STOP_SEC_OsTask_CODE
    #if defined OS_START_SEC_OsTask_CODE
        #undef OS_START_SEC_OsTask_CODE /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef OS_STOP_SEC_OsTask_CODE /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "OS_STOP_SEC_OsTask_CODE: This section has not been previously started!"
    #endif
#elif defined OS_START_SEC_OsTask_CODE
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "OS_START_SEC_OsTask_CODE: Another section which is previously started has not been stopped!"
    #endif

/** OS - OsTask_CONST *********************************************************/
#elif defined OS_STOP_SEC_OsTask_CONST
    #if defined OS_START_SEC_OsTask_CONST
        #undef OS_START_SEC_OsTask_CONST /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef OS_STOP_SEC_OsTask_CONST /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "OS_STOP_SEC_OsTask_CONST: This section has not been previously started!"
    #endif
#elif defined OS_START_SEC_OsTask_CONST
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "OS_START_SEC_OsTask_CONST: Another section which is previously started has not been stopped!"
    #endif

/** OS - OsTask_VAR_INIT ******************************************************/
#elif defined OS_STOP_SEC_OsTask_VAR_INIT
    #if defined OS_START_SEC_OsTask_VAR_INIT
        #undef OS_START_SEC_OsTask_VAR_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef OS_STOP_SEC_OsTask_VAR_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "OS_STOP_SEC_OsTask_VAR_INIT: This section has not been previously started!"
    #endif
#elif defined OS_START_SEC_OsTask_VAR_INIT
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "OS_START_SEC_OsTask_VAR_INIT: Another section which is previously started has not been stopped!"
    #endif

/** OS - OsTask_VAR_NO_INIT ***************************************************/
#elif defined OS_STOP_SEC_OsTask_VAR_NO_INIT
    #if defined OS_START_SEC_OsTask_VAR_NO_INIT
        #undef OS_START_SEC_OsTask_VAR_NO_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef OS_STOP_SEC_OsTask_VAR_NO_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "OS_STOP_SEC_OsTask_VAR_NO_INIT: This section has not been previously started!"
    #endif
#elif defined OS_START_SEC_OsTask_VAR_NO_INIT
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "OS_START_SEC_OsTask_VAR_NO_INIT: Another section which is previously started has not been stopped!"
    #endif

/** OS - Os_ComTask_STACK_VAR_NO_INIT *****************************************/
#elif defined OS_STOP_SEC_Os_ComTask_STACK_VAR_NO_INIT
    #if defined OS_START_SEC_Os_ComTask_STACK_VAR_NO_INIT
        #undef OS_START_SEC_Os_ComTask_STACK_VAR_NO_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef OS_STOP_SEC_Os_ComTask_STACK_VAR_NO_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "OS_STOP_SEC_Os_ComTask_STACK_VAR_NO_INIT: This section has not been previously started!"
    #endif
#elif defined OS_START_SEC_Os_ComTask_STACK_VAR_NO_INIT
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "OS_START_SEC_Os_ComTask_STACK_VAR_NO_INIT: Another section which is previously started has not been stopped!"
    #endif

/** OS - Os_ModeTask_STACK_VAR_NO_INIT ****************************************/
#elif defined OS_STOP_SEC_Os_ModeTask_STACK_VAR_NO_INIT
    #if defined OS_START_SEC_Os_ModeTask_STACK_VAR_NO_INIT
        #undef OS_START_SEC_Os_ModeTask_STACK_VAR_NO_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef OS_STOP_SEC_Os_ModeTask_STACK_VAR_NO_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "OS_STOP_SEC_Os_ModeTask_STACK_VAR_NO_INIT: This section has not been previously started!"
    #endif
#elif defined OS_START_SEC_Os_ModeTask_STACK_VAR_NO_INIT
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "OS_START_SEC_Os_ModeTask_STACK_VAR_NO_INIT: Another section which is previously started has not been stopped!"
    #endif

/** OS - Os_OsTask_STACK_VAR_NO_INIT ******************************************/
#elif defined OS_STOP_SEC_Os_OsTask_STACK_VAR_NO_INIT
    #if defined OS_START_SEC_Os_OsTask_STACK_VAR_NO_INIT
        #undef OS_START_SEC_Os_OsTask_STACK_VAR_NO_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef OS_STOP_SEC_Os_OsTask_STACK_VAR_NO_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "OS_STOP_SEC_Os_OsTask_STACK_VAR_NO_INIT: This section has not been previously started!"
    #endif
#elif defined OS_START_SEC_Os_OsTask_STACK_VAR_NO_INIT
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "OS_START_SEC_Os_OsTask_STACK_VAR_NO_INIT: Another section which is previously started has not been stopped!"
    #endif

/** OS - Os_STARTUP_STACK_VAR_NO_INIT *****************************************/
#elif defined OS_STOP_SEC_Os_STARTUP_STACK_VAR_NO_INIT
    #if defined OS_START_SEC_Os_STARTUP_STACK_VAR_NO_INIT
        #undef OS_START_SEC_Os_STARTUP_STACK_VAR_NO_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef OS_STOP_SEC_Os_STARTUP_STACK_VAR_NO_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "OS_STOP_SEC_Os_STARTUP_STACK_VAR_NO_INIT: This section has not been previously started!"
    #endif
#elif defined OS_START_SEC_Os_STARTUP_STACK_VAR_NO_INIT
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "OS_START_SEC_Os_STARTUP_STACK_VAR_NO_INIT: Another section which is previously started has not been stopped!"
    #endif

/** OS - Os_ComTask_CONTEXT_VAR_NO_INIT ***************************************/
#elif defined OS_STOP_SEC_Os_ComTask_CONTEXT_VAR_NO_INIT
    #if defined OS_START_SEC_Os_ComTask_CONTEXT_VAR_NO_INIT
        #undef OS_START_SEC_Os_ComTask_CONTEXT_VAR_NO_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef OS_STOP_SEC_Os_ComTask_CONTEXT_VAR_NO_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "OS_STOP_SEC_Os_ComTask_CONTEXT_VAR_NO_INIT: This section has not been previously started!"
    #endif
#elif defined OS_START_SEC_Os_ComTask_CONTEXT_VAR_NO_INIT
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "OS_START_SEC_Os_ComTask_CONTEXT_VAR_NO_INIT: Another section which is previously started has not been stopped!"
    #endif

/** OS - Os_ModeTask_CONTEXT_VAR_NO_INIT **************************************/
#elif defined OS_STOP_SEC_Os_ModeTask_CONTEXT_VAR_NO_INIT
    #if defined OS_START_SEC_Os_ModeTask_CONTEXT_VAR_NO_INIT
        #undef OS_START_SEC_Os_ModeTask_CONTEXT_VAR_NO_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef OS_STOP_SEC_Os_ModeTask_CONTEXT_VAR_NO_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "OS_STOP_SEC_Os_ModeTask_CONTEXT_VAR_NO_INIT: This section has not been previously started!"
    #endif
#elif defined OS_START_SEC_Os_ModeTask_CONTEXT_VAR_NO_INIT
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "OS_START_SEC_Os_ModeTask_CONTEXT_VAR_NO_INIT: Another section which is previously started has not been stopped!"
    #endif

/** OS - Os_OsTask_CONTEXT_VAR_NO_INIT ****************************************/
#elif defined OS_STOP_SEC_Os_OsTask_CONTEXT_VAR_NO_INIT
    #if defined OS_START_SEC_Os_OsTask_CONTEXT_VAR_NO_INIT
        #undef OS_START_SEC_Os_OsTask_CONTEXT_VAR_NO_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef OS_STOP_SEC_Os_OsTask_CONTEXT_VAR_NO_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "OS_STOP_SEC_Os_OsTask_CONTEXT_VAR_NO_INIT: This section has not been previously started!"
    #endif
#elif defined OS_START_SEC_Os_OsTask_CONTEXT_VAR_NO_INIT
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "OS_START_SEC_Os_OsTask_CONTEXT_VAR_NO_INIT: Another section which is previously started has not been stopped!"
    #endif

/** OS - Os_STARTUP_CONTEXT_VAR_NO_INIT ***************************************/
#elif defined OS_STOP_SEC_Os_STARTUP_CONTEXT_VAR_NO_INIT
    #if defined OS_START_SEC_Os_STARTUP_CONTEXT_VAR_NO_INIT
        #undef OS_START_SEC_Os_STARTUP_CONTEXT_VAR_NO_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef OS_STOP_SEC_Os_STARTUP_CONTEXT_VAR_NO_INIT /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "OS_STOP_SEC_Os_STARTUP_CONTEXT_VAR_NO_INIT: This section has not been previously started!"
    #endif
#elif defined OS_START_SEC_Os_STARTUP_CONTEXT_VAR_NO_INIT
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "OS_START_SEC_Os_STARTUP_CONTEXT_VAR_NO_INIT: Another section which is previously started has not been stopped!"
    #endif

/******************************************************************************/
/** Os SWC                                                                   **/
/******************************************************************************/

/** Os - PUBLIC_CODE **********************************************************/
#elif defined Os_STOP_SEC_PUBLIC_CODE
    #if defined Os_START_SEC_PUBLIC_CODE
        #undef Os_START_SEC_PUBLIC_CODE /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef Os_STOP_SEC_PUBLIC_CODE /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_STARTED /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode STOP */
        /* END: Addressing Mode STOP */
    #else
        #error "Os_STOP_SEC_PUBLIC_CODE: This section has not been previously started!"
    #endif
#elif defined Os_START_SEC_PUBLIC_CODE
    #ifndef MEMMAP_SECTION_STARTED
        #define MEMMAP_SECTION_STARTED
        #undef MEMMAP_SECTION_NOT_FOUND /* KW MISRA.UNDEF VIOLATION AUTOSAR requirement to be implemented this way */
        /* BEGIN: Addressing Mode START */
        /* END: Addressing Mode START */
    #else
        #error "Os_START_SEC_PUBLIC_CODE: Another section which is previously started has not been stopped!"
    #endif

#endif


#if defined MEMMAP_SECTION_NOT_FOUND
    #error "Section not found in Os_MemMap.h"
#endif

/*====================== EXTERNAL VARIABLE DECLARATIONS ======================*/

/*====================== EXTERNAL FUNCTION DECLARATIONS ======================*/

/*========================= END OF FILE Os_MemMap.h ==========================*/

/* KW MISRA.INCGUARD VIOLATION AUTOSAR requirement to be implemented this way.
   Neither executable code nor symbols are included (only pragmas), thus this violation is
   an approved exception without side effects. */

/* KW MISRA.PRAGMA VIOLATION Each #pragma usage comes from user configuration */
