/* Copyright 2016 Mentor Graphics Corporation
    All Rights Reserved

 THIS WORK CONTAINS TRADE SECRET
 AND PROPRIETARY INFORMATION WHICH IS THE
 PROPERTY OF MENTOR GRAPHICS
 CORPORATION OR ITS LICENSORS AND IS
 SUBJECT TO LICENSE TERMS.
*/
/*****************************************************************************
*        File: COM_PBcfg.h
*        Description: This is the AUTOSAR Com Module Configuration Header File
*                     generated for Link Time and Post Build implementation.
*                           DO NOT EDIT THIS FILE
*        Product:  VSTAR COM
*        Assumptions: none.
*        Dependency: none.
*****************************************************************************/
#ifndef COM_PBCFG_H
#define COM_PBCFG_H

#include "Com_Types.h"

#define COM_START_SEC_CONST_POSTBUILD_UNSPECIFIED
#include "Com_MemMap.h"  /* KW MISRA.INCL.INSIDE */
extern CONST(Com_ConfigType, COM_CONST_PB) ComConfig;
#define COM_STOP_SEC_CONST_POSTBUILD_UNSPECIFIED
#include "Com_MemMap.h"  /* KW MISRA.INCL.INSIDE */


/* PRQA S 0779-- */
#endif /*COM_PBCFG_H*/
/********************************** End of file *******************************/
