/*****************************************************************************
 *
 *              Copyright 2014 Mentor Graphics Corporation
 *                        All rights reserved
 *
 *  THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY INFORMATION WHICH IS
 *  THE PROPERTY OF MENTOR GRAPHICS CORPORATION OR ITS LICENSORS AND IS
 *  SUBJECT TO LICENSE TERMS.
 *
 *****************************************************************************
 *  File: PduR_PBcfg.h
 *  Description: This is the AUTOSAR PduR Module Configuration Header File
 *               generated for Link Time and Post Build implementation.
 *                     CFG tool v[2.4.0]
 *                     DO NOT EDIT THIS FILE
 *  Assumptions: none.
 *  Dependency: none.
 *****************************************************************************/
#ifndef PDUR_PBCFG_H
#define PDUR_PBCFG_H

#include "PduR_Types.h"

#define PDUR_START_SEC_CONST_POSTBUILD_UNSPECIFIED
#include "PduR_MemMap.h" /* KW MISRA.INCL.INSIDE */

extern CONST(PduR_PBConfigType,PDUR_CONST_PB) PduRRoutingTables;

#define PDUR_STOP_SEC_CONST_POSTBUILD_UNSPECIFIED
#include "PduR_MemMap.h" /* KW MISRA.INCL.INSIDE */

#endif /*PduR_PBCFG_H*/
/********************************** End of file *******************************/
