/*****************************************************************************
 *
 *              Copyright 2014 Mentor Graphics Corporation
 *                        All rights reserved
 *
 *  THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY INFORMATION WHICH IS
 *  THE PROPERTY OF MENTOR GRAPHICS CORPORATION OR ITS LICENSORS AND IS
 *  SUBJECT TO LICENSE TERMS.
 *
 *****************************************************************************
 *  File: PduR_Cfg.h
 *  Description: This is the AUTOSAR PduR Module Configuration Header File
 *               generated for Post-Build Implementation.
 *                     CFG tool v[2.4.0]
 *                     DO NOT EDIT THIS FILE
 *
 *  Assumptions: none.
 *  Dependency: none.
 *****************************************************************************/

#ifndef PDUR_CFG_H
#define PDUR_CFG_H

/*****************************************************************************
*                      Include Section
*****************************************************************************/
#include "ComStack_Types.h"


/*****************************************************************************
*                      Global Symbols
*****************************************************************************/
/* Version information */
#define PDUR_CFG_H_AR_VERSION             (422U)
#define PDUR_CFG_H_SW_MAJOR_VERSION       (5U)
#define PDUR_CFG_H_SW_MINOR_VERSION       (11U)


/*Pre-compile options*/

#define PDUR_DEV_ERROR_DETECT                (STD_ON)



#define PDUR_MULTICAST_OPERATION_TP               (STD_OFF)

#define PDUR_MULTICAST_OPERATION_IF               (STD_OFF)

#define PDUR_GATEWAY_OPERATION_IF               (STD_OFF)

#define PDUR_GATEWAY_OPERATION_TP               (STD_OFF)

#define PDUR_ENABLE_ROUTING_GROUPS               (STD_OFF)

#define PDUR_IF_SUPPORT               (STD_ON)

#define PDUR_TP_SUPPORT               (STD_ON)


#define PDUR_VERSION_INFO_API                (STD_ON)
#define PDUR_ENABLE_MINIMUM_ROUTING          (STD_OFF)
#define PDUR_ZERO_COST_OPERATION             (STD_OFF)



 

 
#define CANIF_LOWER_IF_BASE 23U
#define CANIF_TRANSMIT_INDEX 23U
#define CANIF_CANCELTRANSMIT_INDEX 24U

 

 

 
#define CANNM_LOWER_IF_BASE 25U
#define CANNM_TRANSMIT_INDEX 25U
#define CANNM_CANCELTRANSMIT_INDEX 26U

 

 

#define CANTP_LOWER_TP_BASE 27U
#define CANTP_TRANSMIT_INDEX 27U
#define CANTP_CANCELTRANSMITREQUEST_INDEX 28U
#define CANTP_CANCELRECEIVEREQUEST_INDEX 29U
#define CANTP_CHANGEPARAMETERREQUEST_INDEX 30U
  

 



#define COM_UPPER_IF_BASE 31U
#define COM_TRIGGERTRANSMIT_INDEX 31U
#define COM_TXCONFIRMATION_INDEX 32U
#define COM_RXINDICATION_INDEX 33U

 
 


#define DCM_UPPER_TP_RX_BASE 34U
#define DCM_STARTOFRECEPTION_INDEX 34U
#define DCM_COPYRXDATA_INDEX 35U
#define DCM_TPRXINDICATION_INDEX 36U

#define DCM_UPPER_TP_TX_BASE 37U
#define DCM_COPYTXDATA_INDEX 37U
#define DCM_TPTXCONFIRMATION_INDEX 38U



 
 


#define LINDCM_UPPER_TP_RX_BASE 39U
#define LINDCM_STARTOFRECEPTION_INDEX 39U
#define LINDCM_COPYRXDATA_INDEX 40U
#define LINDCM_TPRXINDICATION_INDEX 41U

#define LINDCM_UPPER_TP_TX_BASE 42U
#define LINDCM_COPYTXDATA_INDEX 42U
#define LINDCM_TPTXCONFIRMATION_INDEX 43U



 
 

 

 
#define LINIF_LOWER_IF_BASE 44U
#define LINIF_TRANSMIT_INDEX 44U
#define LINIF_CANCELTRANSMIT_INDEX 45U

 

 

#define LINTP_LOWER_TP_BASE 46U
#define LINTP_TRANSMIT_INDEX 46U
#define LINTP_CANCELTRANSMITREQUEST_INDEX 47U
#define LINTP_CANCELRECEIVEREQUEST_INDEX 48U
#define LINTP_CHANGEPARAMETERREQUEST_INDEX 49U
  

 
 
/* Routing Arrays Indices */
/* CANIF Arrays */
#define PDUR_CANIF_RX_ARRAY_INDEX ((uint8)0)
#define PDUR_CANIF_TX_ARRAY_INDEX ((uint8)1)

/* CANNM Arrays */
#define PDUR_CANNM_RX_ARRAY_INDEX ((uint8)2)
#define PDUR_CANNM_TX_ARRAY_INDEX ((uint8)3)

/* LINIF Arrays */
#define PDUR_LINIF_RX_ARRAY_INDEX ((uint8)4)
#define PDUR_LINIF_TX_ARRAY_INDEX ((uint8)5)

/* CANTP Arrays */
#define PDUR_CANTP_RX_ARRAY_INDEX ((uint8)6)
#define PDUR_CANTP_TX_ARRAY_INDEX ((uint8)7)

/* LINTP Arrays */
#define PDUR_LINTP_RX_ARRAY_INDEX ((uint8)8)
#define PDUR_LINTP_TX_ARRAY_INDEX ((uint8)9)

/* COM Array */
#define PDUR_COM_TX_ARRAY_INDEX ((uint8)10)

/* DCM Array */
#define PDUR_DCM_TX_ARRAY_INDEX ((uint8)11)

/* LINDCM Array */
#define PDUR_LINDCM_TX_ARRAY_INDEX ((uint8)12)

/* DCM Rx Array */
#define PDUR_DCM_RX_UP_ARRAY_INDEX ((uint8)13)

/* LINDCM Rx Array */
#define PDUR_LINDCM_RX_UP_ARRAY_INDEX ((uint8)14)



 
/* Hash key for PduR Pre-Compile configuration */
#define PDUR_PC_HASH_VALUE ((uint32)212217955U)


#endif /*PDUR_CFG_H*/
/********************************** End of file *******************************/
