/* Copyright 2020 Mentor Graphics Corporation 
    All Rights Reserved 
 
 THIS WORK CONTAINS TRADE SECRET 
 AND PROPRIETARY INFORMATION WHICH IS THE 
 PROPERTY OF MENTOR GRAPHICS 
 CORPORATION OR ITS LICENSORS AND IS 
 SUBJECT TO LICENSE TERMS. 
*/ 
#ifndef VSTAR_BITS_MEMMAP_H
#define VSTAR_BITS_MEMMAP_H

#define VSTAR_Bits_CODE 

#endif /* VSTAR_BITS_MEMMAP_H */